<style>

#signup-box {
    width: 450px;
    padding-bottom: 20px;
    border: 1px solid silver;
    -moz-border-radius: 6px;
    -webkit-border-radius: 6px;
    border-radius: 6px;
    background: whiteSmoke;
    background: -webkit-gradient(linear, center top, center bottom, from(white), to(whiteSmoke));
    background: -moz-linear-gradient(top, white, whiteSmoke);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffffff', endColorstr='#fff5f5f5', GradientType=0);

}

.input-text {
    width: 406px;
    position: relative;
    margin: 12px auto 0 auto;
    cursor: text;
}

.input-text input {
    font-family: "Lucida Grande", "Lucida Sans", "Lucida Sans Unicode", Verdana, Arial, Helvetica, sans-serif;
    font-size: 15px;
    width: 385px;
    padding: 10px;
    border: 1px solid #D2D2D2;

    -webkit-border-radius: 0.3em;
    box-shadow: inset -1px 1px 1px 0 rgba(0, 0, 0, 0.1);
    border-radius: 0.3em;
}

.input-checkbox {
    margin: 20px 20px 0px 20px;
    color: #848484;
}
.input-checkbox input {
    float: left;
    width: 20px;
    margin-top: 2px;
}
.input-checkbox label {
    float: left;
    width: 380px;
    margin-left: 10px;
}

.form-action {
    clear: both;
    margin: 0;
    padding: 0;
    margin-left: 20px;
    padding-top: 25px;
}

.form-action input[type=submit] {
    /*font-size: 18px;
    font-family: "HelveticaNeue","Helvetica Neue","HelveticaNeueRoman","HelveticaNeue-Roman","Helvetica Neue Roman","TeXGyreHerosRegular","Helvetica","Tahoma","Geneva","Arial",sans-serif;
    -webkit-appearance: push-button;
    white-space: pre;*/
}

input#create-user {
    min-width: 195px;
}

.button {
    border: 1px solid #459A00;
    background: #4AA400;
    background: -webkit-gradient(linear, center top, center bottom, from(#5CCD00), to(#4AA400));
    background: -moz-linear-gradient(top, #5CCD00, #4AA400);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff5ccd00', endColorstr='#ff4aa400', GradientType=0);
    display: inline-block;
    text-align: center;
    min-height: 2em;
    cursor: pointer;
    -moz-border-radius: 0.3em;
    -webkit-border-radius: 0.3em;
    border-radius: 0.3em;
    line-height: 2em;
    padding: 0 1em;
    font-size: 1.15em;
    font-weight: bold;
    color: white !important;
    text-shadow: 0 -1px 1px rgba(0, 0, 0, 0.5);
    text-decoration: none;
    -o-box-shadow: inset 0 0 0.2em rgba(255,255,255,0.3),0 1px 2px rgba(0,0,0,0.3);
    -moz-box-shadow: inset 0 0 0.2em rgba(255,255,255,0.3),0 1px 2px rgba(0,0,0,0.3);
    -webkit-box-shadow: inset 0 0 0.2em rgba(255, 255, 255, 0.3),0 1px 2px rgba(0, 0, 0, 0.3);
    box-shadow: inset 0 0 0.2em rgba(255, 255, 255, 0.3),0 1px 2px rgba(0, 0, 0, 0.3);
    font-family: "HelveticaNeue","Helvetica Neue","HelveticaNeueRoman","HelveticaNeue-Roman","Helvetica Neue Roman","TeXGyreHerosRegular","Helvetica","Tahoma","Geneva","Arial",sans-serif;
    font-size: 18px;
}

/*
 input[type="text"], input[type="password"], input[type="date"], input[type="search"], textarea {
    padding: 0.3em 0.4em;

}
*/
</style>

<div>

<h2>Sign-up for HPW</h2>
<form accept-charset="utf-8" action="<?php echo $this->form->getAction() ?>" class="user_new" data-action="Signup" id="user_new" method="<?php echo $this->form->getMethod() ?>">
<div id="signup-box">
    <div class="input-text">
        <input id="user_first_name" name="firstname" value="<?php echo $this->escape($this->form->getValue('firstname')) ?>" placeholder="First name" size="30" type="text">
        <?php echo $this->displayErrors($this->form->getMessages('firstname')) ?>
    </div>

    <div class="input-text" id="inputEmail">
        <input id="user_email" name="emailAddress" value="<?php echo $this->escape($this->form->getValue('emailAddress')) ?>" placeholder="Email Address" size="30" type="text" />
        <?php echo $this->displayErrors($this->form->getMessages('emailAddress')) ?>
	</div>

    <div class="input-text" id="inputPassword">
        <input id="user_password" name="passwd" placeholder="Password" size="30" type="password" />
        <?php echo $this->displayErrors($this->form->getMessages('passwd')) ?>
	</div>

    <!--
    <div class="input-checkbox">
        <input name="user_profile_info[opt_in_promotional_email]" type="hidden" value="0" /><input checked="checked" id="user_profile_info_opt_in_promotional_email" name="user_profile_info[opt_in_promotional_email]" type="checkbox" value="1" />
        <label for="user_profile_info_opt_in_promotional_email">Tell me about inspiring travel tidbits, juicy Airbnb news, and exclusive discounts!</label>
    </div>
    -->

    <div class="form-action">
        <input type="submit" id="create-user" class="button" value="Create Account">
    </div>
</div>
</form>

</div>
