#!/bin/bash
cd /var/www/beta.holidaypropertyworldwide.com/
tar zxfp app.tar.gz

directory="./data"
if [ ! -d $directory ]; then
	mkdir data
	mkdir data/logs
	touch data/logs/application.log
    mkdir data/session
	chmod g+rw data/logs/application.log
else
	if [ ! -d "./data/logs" ]; then
		mkdir data/logs
		touch data/logs/application.log
		chmod g+rw data/logs/application.log
	fi
    
    if [ ! -d "./data/session" ]; then
        mkdir data/session
    fi
fi

rm /var/www/beta.holidaypropertyworldwide.com/app.tar.gz
mv /var/www/beta.holidaypropertyworldwide.com/public/.htaccess-beta /var/www/beta.holidaypropertyworldwide.com/public/.htaccess
chgrp devteam -fR *
