<h1>Advertiser Account Management</h1>
<p><?php echo $this->name ?>, welcome to the account management control panel. Within the control panel you can add, edit property details including uploading photographs</p>
<p>If this is your first visit, we suggest you begin by clicking "Add a new property" from the form below.</p>

<p>Use the link below if you wish to add a new property to your account.</p>
<a href="<?php echo $this->url(array('controller' => 'advertiser-property',
                                     'action'     => 'step1-location',
                                     'module'     => 'frontend')) ?>">[add a new property]</a>

<table cellpadding="0" cellspacing="0" border="1">
<?php foreach ($this->propertyRowset as $row) : ?>
<tr>
    <td><?php echo $this->propertyTinyThumb($row->idProperty, $this->photoRowsetLookup) ?></td>
    <td>
		<p>Ref: <?php echo $row->idProperty ?> <?php echo $this->propertyType($row->idPropertyType) ?>  <?php echo $this->escape($row->shortName) ?>
		<?php echo $row->numBeds ?> beds. Sleeps <?php echo $row->numSleeps ?>
		<?php echo $this->holidayType($row->idHolidayType) ?>
		(Expires: <?php echo $this->prettyDate($row->expiry) ?>)</p><?php echo $this->summaryBar($row) ?>
	</td>
    <td><?php echo $this->advertiserControlPanelStatus($row) ?></td>
</tr>
<?php endforeach ?>
</table>
