<h1>List Awaiting Initial Approval</h1>


<div id="seturl-form" title="Set the URL">
	<form>
	<fieldset>
		<label for="setUrl">URL</label>
        <input type="text" name="setUrl" id="setUrl" value="abc" class="text ui-widget-content" />
		<!--<input type="text" name="setUrl" id="setUrl" value="abc" class="text ui-widget-content ui-corner-all" />-->
	</fieldset>
	</form>
</div>


<?php if ($this->propertyRowset == null) : ?>
<p>There are currently no properties awaiting initial approval.</p>
<?php endif ?>


<?php if ($this->propertyRowset) : ?>
<table style="width:100%">
    <tr>
        <th>Property Id</th>
        <th>Type</th>
        <th>Location</th>
        <th>Created On</th>
        <th>URL</th>
		<th>Expiry date</th>
        <th>Approve Property</th>
    </tr>
    <?php foreach ($this->propertyRowset as $row) : ?>
	<tr>
		<td><?php echo $row->idProperty ?></td>
		<td><?php echo $this->propertyType($row->idPropertyType) ?></td>
		<td><?php echo $this->approvalLocation($row->idProperty, $row->idLocation) ?></td>
		<td><?php echo $this->prettyDate($row->added) ?></td>
		<td><?php echo $this->locationUrl($row->idProperty, $row->urlName) ?></td>
		<td><?php echo $this->propertyExpiry($row->idProperty, $row->expiry) ?></td>
		<td><?php echo $this->approveProperty($row->idProperty, $row->idLocation, $row->urlName, $row->expiry) ?></td>
	</tr>
    <?php endforeach ?>
</table>
<?php endif ?>