<form enctype="application/x-www-form-urlencoded" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>" />
<input type="hidden" name="do" value="delete" />
<input type="hidden" name="idProperty" value="<?php echo $this->form->getValue('idProperty') ?>" />
<input type="hidden" name="idAvailability" value="<?php echo $this->form->getValue('idAvailability') ?>" />
<input type="hidden" name="digestKey" value="<?php echo $this->form->getValue('digestKey') ?>" />
<fieldset>
    <dl>
        <dt>Start date</dt>
        <dd><?php echo $this->prettyDate($this->availabilityRow->startDate) ?></dd>
        
        <dt>End date</dt>
        <dd><?php echo $this->prettyDate($this->availabilityRow->endDate) ?></dd>
        
        <dt>Confirm</dt>
        <dd><input type="submit" value="Delete" /></dd> 
    </dl>
</fieldset>
</form>

<form enctype="application/x-www-form-urlencoded" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>" />
<input type="hidden" name="idProperty" value="<?php echo $this->idProperty ?>" />
<input type="hidden" name="idAvailability" value="<?php echo $this->form->getValue('idAvailability') ?>" />
<input type="hidden" name="digestKey" value="<?php echo $this->form->getValue('digestKey') ?>" />
<input type="hidden" name="do" value="cancel" />
<input type="submit" value="Cancel" />
</form>