<h1>New Advertisers</h1>
<p>To advertise your rental properties you will need to first setup an online account. Account registration is quick, easy. Just simply complete the single page form below and press send. If you already an existing member you can <a href="/alogin/">login here.</a></p>

<div class="form">
<h1>Register to advertise your properties</h1>
<form method="post" action="/aregister/">
<input type="hidden" name="idAdministrators" value="<?php echo $this->P('idAdministrators') ?>" />
<input type="hidden" name="action" value="register" />
<fieldset>
	<?php echo $this->X('errors_below') ?>
	<dl>
		<dt><label for="firstname">Firstname: <span class="astrix">*</span></label></dt>
		<dd><input type="text" maxlength="128" id="firstname" name="firstname" value="<?php echo $this->firstname ?>" /><?php //echo $this->E('firstname') ?></dd>
	</dl>
	<dl>
		<dt><label for="lastname">Lastname: <span class="astrix">*</span></label></dt>
		<dd><input type="text" maxlength="128" id="lastname" name="lastname" value="<?php echo $this->lastname ?>" /><?php //echo $this->E('lastname') ?></dd>
	</dl>
	<dl>
		<dt><label for="country">Email address: <span class="astrix">*</span></label></dt>
		<dd><input type="text" maxlength="255" size="40" name="emailAddress" value="<?php echo $this->P('emailAddress') ?>" /><?php //echo $this->E('emailAddress') ?></dd>
	</dl>
	<dl>
		<dt><label for="passwd">Choose a password: <span class="astrix">*</span></label></dt>
		<dd><input type="password" name="passwd" maxlength="32" value="<?php echo $this->P('passwd') ?>" /><?php //echo $this->E('passwd') ?></dd>
	</dl>
	<dl>
		<dt><label for="passwdc">Repeat your password: <span class="astrix">*</span></label></dt>
		<dd><input type="password" name="passwdc" maxlength="32" value="<?php echo $this->passwdc ?>" /><?php //echo $this->E('passwdc') ?></dd>
	</dl>
	<dl>
		<dt>&nbsp;</dt>
		<dd><input class="button1" type="submit" id="submit" name="submit" value="Send" /></dd>
	</dl>
</form>
</div>
<p>Privacy policy: All information which you provide will be treated as strictly confidential. We guarantee that none of your personal information will be passed on to any other company, organisation or individual.</p>