<h1>New Advertisers</h1>
<p>To advertise your rental properties you will need to first setup an online account. Account registration is quick, easy. Just simply complete the single page form below and press send. If you already an existing member you can
<a href="<?php echo $this->url(array('module' => 'frontend',
                                     'controller' => 'advertiser-',
                                     'action' => 'login')); ?>">login here.</a></p>
<?php echo $this->form ?>
<p>Privacy policy: All information which you provide will be treated as strictly confidential. We guarantee that none of your personal information will be passed on to any other company, organisation or individual.</p>