<h1>Request for Permission</h1>
<p>Application <?php echo $this->appName ?> is requesting permission to do the following:</p>

<div id="hpw-permission-frame">
    <div id="hpw-scopes">
    </div>

    <div id="hpw-app">
    </div>
</div>

Logged in as <?php echo $this->loginContactName ?> <a href="#">(Not You?)</a>


<form id="hpw-allow-disallow-form" enctype="application/x-www-form-urlencoded" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
<input type="hidden" name="response_type" value="<?php echo $this->form->getValue('responseType') ?>" />
<input type="hidden" name="client_id" value="<?php echo $this->form->getValue('clientId') ?>" />
<input type="hidden" name="redirect_uri" value="<?php echo $this->form->getValue('redirectUri') ?>" />
<input type="hidden" name="scope" value="<?php echo $this->form->getValue('scope') ?>" />
<input type="hidden" name="state" value="<?php echo $this->form->getValue('state') ?>" />

<button name="allow" value="1" id="hpw-allow">Allow</button>
<button name="allow" value="0"  id="hpw-disallow">Don't Allow</button>
</form>
