<div id="browse_country">
    <h1>Regions in <?php echo $this->escape($this->countryName) ?></h1>
    <?php if ($this->fastLookupRowset) : ?>
    <ul>
        <?php foreach ($this->fastLookupRowset as $row): ?>
        <li><a href="/in/<?php echo $row->url ?>"><?php echo $this->escape($row->regionName) ?> (<?php echo $row->totalVisible ?>)</a></li>
        <?php endforeach ?>
    </ul>
    <?php else : ?>
    <p>There are currently no properties in <?php echo $this->escape($this->countryName) ?>.</p>
    <?php endif ?>
</div>

<?php if ($this->showFeatured) : ?>
<div class="yui-gb">
    <div class="yui-u first"><?php echo $this->featuredPartials[0] ?></div>
    <div class="yui-u"><?php echo $this->featuredPartials[1] ?></div>
    <div class="yui-u"><?php echo $this->featuredPartials[2] ?></div>
</div>
<?php endif ?>

<?php if ($this->showProperties) : ?>
<div>
    <h1>Properties in <?php echo $this->countryName ?> (<?php echo $this->fastLookupRow->totalVisible ?>)</h1>
    <ul>
        <?php foreach ($this->partials as $partial): ?>
        <li><?php echo $partial ?></li>
        <?php endforeach ?>
    </ul>
</div>
<?php endif ?>