<div id="browse_country">
    <?php //var_dump($this->locationRow) ?>
    <h1>Regions in <?php echo $this->escape($this->locationRow->name) ?></h1>
    <?php if ($this->locationRowset) : ?>
    <ul>
        <?php foreach ($this->locationRowset as $row): ?>
            <?php if ($row->totalVisible > 0) : ?>
            <li><a href="<?php echo $row->url ?>"><?php echo $this->escape($row->rowname) ?> (<?php echo $row->totalVisible ?>)</a></li>
            <?php endif ?>
        <?php endforeach ?>
    </ul>
    <?php else : ?>
    <p>There are currently no properties in <?php echo $this->escape($this->countryName) ?>.</p>
    <?php endif ?>
</div>

<?php if ($this->showFeatured) : ?>
<div class="yui-gb">
    <div class="yui-u first"><?php echo $this->featuredPartials[0] ?></div>
    <div class="yui-u"><?php echo $this->featuredPartials[1] ?></div>
    <div class="yui-u"><?php echo $this->featuredPartials[2] ?></div>
</div>
<?php endif ?>

<?php if ($this->showProperties) : ?>
<div>
    <h1>Properties in <?php echo $this->escape($this->locationRow->name) ?> (<?php echo $this->locationRow->totalVisible ?>)</h1>
    <ul>
        <?php foreach ($this->partials as $partial): ?>
        <li><?php echo $partial ?></li>
        <?php endforeach ?>
    </ul>
</div>
<?php endif ?>