<?php //die('dest'); ?>
<h1>Properties in <?php echo $this->locationBreadcrumb(
                                        $this->locationRow->idLocation,
                                        array (
                                            'totalsMode' => Vfr_View_Helper_LocationBreadcrumb::TOTALS_ALL_NODES
                                        )) ?></h1>
<?php if ($this->showFeatured) : ?>
<div class="yui-gb">
    <div class="yui-u first"><?php echo $this->featuredPartials[0] ?></div>
    <div class="yui-u"><?php echo $this->featuredPartials[1] ?></div>
    <div class="yui-u"><?php echo $this->featuredPartials[2] ?></div>
</div>
<?php endif ?>
xxx
<?php if ($this->showProperties) : ?>
<div>
    <ul>
        <?php foreach ($this->partials as $partial): ?>
        <li><?php echo $partial ?></li>
        <?php endforeach ?>
    </ul>
</div>
<?php else : ?>
<div>
<p>There are currently no properties in this destination.</p>
</div>
<?php endif ?>