<?php //var_dump($this->locationRow) ?>
<div id="browse_country">
    <h1>Destinations in <?php echo $this->locationBreadcrumb(
                                        $this->locationRow->idLocation,
                                        array (
                                            'totalsMode' => Vfr_View_Helper_LocationBreadcrumb::TOTALS_ALL_NODES
                                        )) ?></h1>
    <?php if ($this->locationRowset) : ?>
    <ul>
        <?php foreach ($this->locationRowset as $row): ?>
            <?php if ($row->totalVisible > 0) : ?>
            <li><a href="/<?php echo $row->url ?>"><?php echo $this->escape($row->rowname) ?> (<?php echo $row->totalVisible ?>)</a></li>
            <?php endif ?>
        <?php endforeach ?>
    </ul>
    <?php else : ?>
    <p>There are currently no properties in <?php echo $this->escape($this->regionName) ?>.</p>
    <?php endif ?>
</div>

<?php if ($this->showFeatured) : ?>
<div class="yui-gb">
    <div class="yui-u first"><?php // echo $this->featuredPartials[0] ?></div>
    <div class="yui-u"><?php // echo $this->featuredPartials[1] ?></div>
    <div class="yui-u"><?php // echo $this->featuredPartials[2] ?></div>
</div>
<?php endif ?>

<div>
    <?php //echo $this->locationBreadcrumb(77) ?>
    <?php //die('bailout') ?>

   <h1>Properties in <?php echo $this->locationBreadcrumb($this->locationRow->idLocation) ?></h1>
    <?php if ($this->showProperties) : ?>
    <ul>
        <?php foreach ($this->partials as $partial): ?>
        <li><?php echo $partial ?></li>
        <?php endforeach ?>
    </ul>
    <?php else : ?>
    <p>There are currently no properties in this region.</p>
    <?php endif ?>
</div>