<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<?php echo $this->headLink() ?>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headMeta() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headStyle() ?>
	<?php
    if ($this->jQuery()->isEnabled()) {
        $this->jQuery()->setLocalPath('/js/jquery/jquery-1.7.1.min.js')
                       ->setUiLocalPath('/js/jquery-ui-1.8.12/ui/jquery-ui.js')
                       ->addStylesheet('/js/jquery-ui-themes-1.8.12/themes/sunny/jquery-ui.css');
        echo $this->jQuery();
    }
    ?>
	<?php echo $this->headScript() ?>
	<?php echo $this->headLink()->prependStylesheet('/js/yui2/reset-fonts-grids/reset-fonts-grids.css') ?>
	<link href="/css/admin/controlpanel.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="doc4">
	<div id="hd">
	</div>
	
	<div id="zf-navbar">
		
		<?php //echo $this->navigation()->menu() ?>
	</div>
	
	<div id="navbar">
		<?php echo $this->navigation()->menu()->setRenderParents(true)->setPartial('partials/admin-nav.phtml') ?>
		<?php //echo $this->navigation()->menu()->setMaxDepth(0); ?>
		<?php //echo $this->navigation()->menu()->setOnlyActiveBranch(true)->setRenderParents(false)->setMinDepth(1)->setMaxDepth(1); ?>
	</div>
	
	<div id="bd">
		<div id="yui-main">
			<div class="yui-b"><?php echo $this->layout()->content ?></div>
		</div>
		
		<div class="yui-b">
		</div>
	</div>
		
	<div id="ft">
	</div>
</div>
</body>
</html>