<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<?php echo $this->headLink() ?>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headMeta() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headStyle() ?>
	<?php
    if ($this->jQuery()->isEnabled()) {
        $this->jQuery()->setLocalPath('/js/jquery/jquery-1.6.min.js')
                       ->setUiLocalPath('/js/jquery-ui-1.8.12/ui/jquery-ui.js')
                       ->addStylesheet('/js/jquery-ui-themes-1.8.12/themes/sunny/jquery-ui.css');
        echo $this->jQuery();
    }
    ?>
	<?php echo $this->headScript() ?>
	<?php echo $this->headLink()->prependStylesheet('/js/yui2/reset-fonts-grids/reset-fonts-grids.css') ?>
	<link href="/css/admin/controlpanel.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="doc4">
	<div id="hd">
	</div>
	
	<div id="navbar">
		<ul id="projects" class="clearfix">
			<li><a href="<?php echo $this->url(
				array (
					'module' => 'admin',
					'controller' => 'index',
					'action' => 'index')) ?>" title="Overview">Overview</a></li>
			<li><a href="<?php echo $this->url(
				array (
					'module' => 'admin',
					'controller' => 'advertiser',
					'action' => 'index',
					'page' => 1)) ?>" title="Advertisers">Advertisers</a></li>
			<li><a href="<?php echo $this->url(
				array (
					'module' => 'admin',
					'controller' => 'member',
					'action' => 'index')) ?>" title="Members">Members</a></li>
			<li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'administrator', 'action' => 'index')) ?>" title="Administrators">Administrators</a></li>
			<li class="selected"><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'properties', 'action' => 'index')) ?>" title="Properties">Properties</a></li>
			<li><a href="/projects/yui3/">YUI 3</a></li>
			<li><a href="/labs/" class="labs">YUI Labs</a></li>
			<li><a href="/projects/yuicompressor/">YUI Compressor</a></li>
			<li><a href="/projects" class="more">More</a></li>
		</ul>
			
		<div id="sections" class="clearfix">
			<ul class="clearfix">
				<li><a href="<?php echo $this->url(array(
					'module' 		=> 'admin',
					'controller'	=> 'property',
					'action'		=> 'list'
				)) ?>">List</a></li>
				<li><a href="<?php echo $this->url(array('module' => 'admin',
														 'controller' => 'index',
														 'action' => 'list-awaiting-initial-approval')) ?>">Awaiting Initial Approval</a></li>
				<li><a href="<?php echo $this->url(array('module' => 'admin',
														 'controller' => 'property',
														 'action' => 'list-awaiting-update-approval')) ?>">Awaiting Update Approval</a></li>
				<li><a href="/forum/recent.php">Recent Posts</a></li>
			    <li><a href="./search.php?sid=06f251f9f1c4c7123f1f3ffdcc322fdb">Search</a></li>
				<li><a href="#">Register</a></li>
				<li><a href="#">Login</a></li>
			</ul>
		</div>
	</div>
	
	<div id="bd">
		<div id="yui-main">
			<div class="yui-b"><?php echo $this->layout()->content ?></div>
		</div>
		
		<div class="yui-b">
		</div>
	</div>
		
	<div id="ft">
	</div>
</div>
</body>
</html>
