<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Administration Control Panel</title>
    <meta name="robots" content="noindex, nofollow" />
    <!-- Individual YUI CSS files -->
    <link rel="stylesheet" type="text/css" href="/templates/js/yui_2.8.0r4/build/reset-fonts-grids/reset-fonts-grids.css" />
    <link href="/admin/templates/css/fixed_width_admin.css" type="text/css" lang="en" media="screen" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="/admin/templates/css/yuilib.css" />
    <link rel="stylesheet" type="text/css" href="/templates/js/yui_2.8.0r4/build/assets/skins/sam/skin.css" />
</head>
<body class="yui-skin-sam">
    <div id="doc5">
        <div id="hd">
            <div id="navbar">
                <ul class="clearfix" id="projects">
                    <li><a title="" href="/admin/">Home</a></li>
                    <li class="selected"><a title="" href="/admin/">Gallery</a></li>
                    <li><a title="" href="/admin/">Forums</a></li>

                    <li><a title="" href="/admin/">YUI 2</a></li>
                    <li><a title="" href="/admin/">YUI 3</a></li>
                    <li><a title="" href="/admin/">YUICompressor</a></li>
                    <li><a title="" href="/admin/">YUIDoc</a></li>
                </ul>

                <ul class="clearfix" id="sections">
                    <li class="first"><a title="" href="/admin/">Project Home</a></li>

                    <li><a title="" href="/admin">Wiki</a></li>
                    <li><a title="" href="/admin">Download</a></li>
                    <li><a title="" href="/admin/">Forum</a></li>
                    <li><a title="" href="/admin/">Calendar</a></li>
                    <li><a title="" href="/admin/">Browse Source</a></li>
                    <li><a title="" href="/admin/">Pull Request</a></li>

                    <li class="active"><a title="" href="/admin/">View Tickets</a></li>
                    <li><a title="" href="/admin/">New Ticket</a></li>
                    <li><a title="" href="/admin/">Register</a></li>
                    <li class="last"><a title="Login" href="/admin/">Login</a></li>
                </ul>
            </div>
        </div>

        <div id="bd">
            <div class="yui-u first"><h1>ADMIN HOME</h1><?php echo $this->layout()->content; ?>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>

<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
</div>
                  </div>
                  <span class="corners-bottom"><span></span></span>
        </div>

            </div>
      </div>
      <div id="page-footer">Administration control panel by Greycat Media &copy; 2009 <a href="http://www.greycatmedia.co.uk/">Greycat Media</a></div>
</div>
</body>
</html>