<div class="form">
<h1>Step 4 - Rental Basis</h1>
<ul id="property_progress_header">
	<li id="location_orange"></li>
	<li id="content_orange"></li>
	<li id="pictures_orange"></li>
	<li id="rates_grey"></li>
	<li id="availability_grey"></li>
</ul>
<p class="clearfix" />

<form enctype="application/x-www-form-urlencoded" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
<input type="hidden" name="idProperty" value="<?php echo $this->idProperty ?>" />
	<fieldset>
		<legend>Rental Basis</legend>
		
		<dt>
			<label for="rentalBasis">Type of property:</label>
		</dt>
		
		<dd>
			<?php echo $this->formSelect('rentalBasis', $this->form->getValue('rentalBasis'), null, $this->form->getElement('rentalBasis')->getMultiOptions()) ?>
		</dd>
		
		<dd>
			<input type="submit" name="submit" value="submit" />
		</dd>
	</fieldset>
</form>

</div>