lookup = [
    'locationUrl',
    'metaData',
    'seoData',
    'websiteUrl',
    'headline1',
    'headline2',
    'summary',
    'description',
    'bedroomDesc',
    'bathroomDesc',

    'kitchenDesc',
    'utilityDesc',
    'livingDesc',
    'otherDesc',
    'serviceDesc',
    'notesDesc',
    'accessDesc',
    'outsideDesc',
    'golfDesc',
    'skiingDesc',

    'specialDesc',
    'beachDesc',
    'travelDesc',
    'bookingDesc',
    'testimonialsDesc',
    'changeoverDesc',
    'contactDesc',
    'country',
    'region',
    'location'
]
