<h2>Confirmation Link Expired or Invalid</h2>
<p>The link you have clicked on has expired.</p>

<p>You will need to <a href="<?php echo $this->url(
                                            array ('module'     => 'frontend',
                                                   'controller' => 'advertiser-registration',
                                                   'action'     => 'register')) ?>">register again</a> and active your advertising account within 48 hours.</p>