<h1>Step 2 - Enter the content for your property</h1>
<ul id="property_progress_header">
	<li id="location_orange"></li>
	<li id="content_grey"></li>
	<li id="pictures_grey"></li>
	<li id="rates_grey"></li>
	<li id="availability_grey"></li>
</ul>
<p class="clearfix" />
<p>Describe the details of your rental property using the form below. Make sure you click the 'save' button at the bottom of the form to ensure your changes are stored.</p>
<p>When you are happy with your content and want it approved, click "Send for approval" in the account home control panel.</p>
<?php echo $this->form ?>