<div class="form">
<h1>Step 5 - Property Availability : <?php echo $this->propertyType($this->propertyRow->idPropertyType) ?> <?php echo $this->escape($this->propertyRow->shortName) ?> - Ref <?php echo $this->propertyRow->idProperty ?></h1>
<ul id="property_progress_header">
	<li id="location_orange"></li>
	<li id="content_orange"></li>
	<li id="pictures_orange"></li>
	<li id="rates_orange"></li>
	<li id="availability_grey"></li>
</ul>
<p class="clearfix" />
<?php echo $this->availabilityNotifier($this->propertyRow) ?>
<p>Select a booking start date and end date to denote a date range, then click 'Book' to apply the booking.</p>

<form enctype="application/x-www-form-urlencoded" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>" />
<input type="hidden" name="idProperty" value="<?php echo $this->propertyRow->idProperty ?>" />
<input type="hidden" name="digestKey" value="<?php echo $this->form->getValue('digestKey') ?>" />
<table>
<tr>
	<th>Start Date</th>
	<th>End Date</th>
	<th>Update</th>
	<th>Delete</th>
</tr>
<?php if ($this->availabilityRowset) : ?>
	<?php foreach ($this->availabilityRowset as $row) : ?>
	<tr>
		<td><?php echo $this->prettyDate($row->startDate) ?></td>
		<td><?php echo $this->prettyDate($row->endDate) ?></td>
		<td><a href="<?php echo $this->url(array('module'    	 => 'frontend',
												'controller'	 => 'advertiser-availability',
												'action'		 => 'edit',
												'idProperty' 	 => $this->propertyRow->idProperty,
												'idAvailability' => $row->idAvailability,
												'digestKey'		 => Vfr_DigestKey::generate(array(
													$this->propertyRow->idProperty,
													$row->idAvailability
												))), null, true) ?>">[edit]</a></td>
		<td><a href="<?php echo $this->url(array('module'         => 'frontend',
												 'controller'     => 'advertiser-availability',
												 'action'         => 'delete-confirm',
												 'idProperty'     => $this->propertyRow->idProperty,
												 'idAvailability' => $row->idAvailability,
												 'digestKey'      => Vfr_DigestKey::generate(array(
													$this->propertyRow->idProperty,
													$row->idAvailability
												 ))), null, true) ?>">[delete]</a></td>
	</tr>
	<?php endforeach ?>
<?php endif ?>
<tr>
	<td><input id="start" type="text" name="availability[start]" value="<?php echo $this->availabilityPicker($this->form->getValue('availability'), 'start') ?>" /></td>
	<td><input id="end" type="text" name="availability[end]" value="<?php echo $this->availabilityPicker($this->form->getValue('availability'), 'end') ?>" /></td>
	<td><input type="submit" name="submit" value="Add Booking" /></td>
</tr>
</table>
<div>
	<?php echo $this->displayErrors($this->form->getMessages('availability')) ?>
</div>
</form>

<img alt="" src="/ic.php?idProperty=<?php echo $this->propertyRow->idProperty ?>" />
</div>