<div class="form">
<h1>Step 4 - Set the property rates</h1>
<ul id="property_progress_header">
	<li id="location_orange"></li>
	<li id="content_orange"></li>
	<li id="pictures_orange"></li>
	<li id="rates_orange"></li>
	<li id="availability_grey"></li>
</ul>
<p class="clearfix" />
<p>Select a booking start date and end date to denote a date range, then click 'Book' to apply the booking.</p>

<?php echo $this->form ?>
</div>