<div class="form">
<h1>Step 3 - Upload your photos</h1>
<ul id="property_progress_header">
	<li id="location_orange"></li>
	<li id="content_orange"></li>
	<li id="pictures_grey"></li>
	<li id="rates_grey"></li>
	<li id="availability_grey"></li>
</ul>
<p class="clearfix" />
<p>Use the form below to upload digital photos of your property. Ensure your photos are of good quality, in focus, and do not contain people, pets or distracting objects not relating to the property.</p>
<p>As an example you might want to include photos of your pool, master bedroom, garden and view from outside. Type an appropriate short caption to describe your photograph.</p>
<?php echo $this->form ?>
</div>