<div class="form">
<h1>Property Completed</h1>
<ul id="property_progress_header">
	<li id="location_green"></li>
	<li id="content_orange"></li>
	<li id="pictures_green"></li>
	<li id="rates_green"></li>
	<li id="availability_green"></li>
</ul>
<p class="clearfix" />

<p>Your content updates have been send for approval.  Meanwhile, you original property is still live.<p>

<p><a href="/advertiser-account/home">Return to my account management home page</a></p>
</div>