<?php
$propertyTypes = $this->P('propertyTypes');
if($this->P('featured_property_list')) {
?><table cellpadding="0" cellspacing="0" width="100%">
<tr>
<?php
$i = 0;
foreach($this->P('featured_property_list') as $id => $property) {
	$photo_list = $property['photo_list'];
	if(sizeof($photo_list) > 0) {
		$idPhotos = key($photo_list);
	} else {
		$idPhotos = null;
	}
?><!-- start featured property box -->
<td valign="top">
<div class="featured_property">
<h1 class="featured_property">Featured <?php echo $propertyTypes[$property['idPropertyTypes']]?> in<br />
<?php echo $this->P('lf')->countryRegionDestinationAsString($property['idCountries'], $property['idRegions'], $property['idDestinations']) ?></h1>
<div class="padded"><p><a href="/in/<?php echo $property['locationURL'] ?>/<?php echo $property['urlName'] ?>"><img
alt="<?php echo $propertyTypes[$property['idPropertyTypes']] ?> <?php echo $property['numBeds'] ?> Bedrooms (Sleeps <?php echo $property['numSleeps'] ?>)" src="/properties/dynamic/<?php echo PropertyMultiplexor::getDirectoryID($id)?>/<?php echo $id ?>/<?php echo $idPhotos . "_150x113.jpg" ?>" /></a></p>
<p><?php echo nl2br(htmlentities($property['content_list'][PropertiesContentDAO::DB_FIELD_HEADLINE_1])) ?></p>
<p><?php echo nl2br(htmlentities($property['content_list'][PropertiesContentDAO::DB_FIELD_HEADLINE_2])) ?></p>
<p><a href="/in/<?php echo $property['locationURL'] ?>/<?php echo $property['urlName'] ?>">more&gt;</a></p>
</div>
</div>
</td>
<!-- end featured property box -->
<?php
if(($i % 3) == 2) {
	?></tr><tr><?
}
}
?></tr>
</table>
<?php
$i++;
}?>