<style>
.left {
    margin: 0;
    margin-right: 30px;
    float: left;
}
.right {
    margin: 0;
    margin-left: 30px;
    float: right;
}
.property-content {
    height: 300px;
    border: 1px solid silver;
    border-radius: 6px;
    padding-top: 12px;
    padding-bottom: 12px;
    padding-left: 25px;
    padding-right: 25px;
    margin-top: 20px;
    margin-bottom: 20px;
}

</style>

<div class="property-content">
<h2><?php echo $this->escape($this->obj->getHeading($this->lang)) ?></h2>
<img width="204" height="136" class="left" alt="<?php echo $this->escape($this->images[0]->getCaption()) ?>" src="/images/location-content/<?php echo $this->images[0]->getUri() ?>">
<?php echo $this->obj->getBody($this->lang, 1)->getContent() ?>
<img width="204" height="136" class="right" alt="<?php echo $this->escape($this->images[1]->getCaption()) ?>" src="/images/location-content/<?php echo $this->images[1]->getUri() ?>">
<?php echo $this->obj->getBody($this->lang, 2)->getContent() ?>
</div>