
Merchant: <?php echo $this->merchant ?><br>
Template: <?php echo $this->template ?><br>
trans_id: <?php echo $this->trans_id ?><br>
backcallback: <?php echo $this->escape($this->backcallback) ?><br>
callback: <?php echo $this->escape($this->callback) ?><br>



<div style="width: 700px; font-family: 'Courier New'; word-break: break-all">URL: <?php echo $this->escape($this->url) ?></div>






<div><a href="<?php echo $this->url ?>">do test transation</a></div>