DROP TABLE IF EXISTS Tree;

CREATE TABLE Tree (
    node CHAR(1) PRIMARY KEY,
    lft INT(2) NOT NULL,
    rgt INT(2) NOT NULL
);

INSERT INTO Tree VALUES ('A', 1, 26);
INSERT INTO Tree VALUES ('B', 2, 9);
INSERT INTO Tree VALUES ('C', 10, 11);
INSERT INTO Tree VALUES ('D', 12, 23);
INSERT INTO Tree VALUES ('E', 24, 25);
INSERT INTO Tree VALUES ('F', 3, 4 );
INSERT INTO Tree VALUES ('G', 5, 6);
INSERT INTO Tree VALUES ('H', 7, 8);
INSERT INTO Tree VALUES ('I', 13, 18);
INSERT INTO Tree VALUES ('J', 19, 20);
INSERT INTO Tree VALUES ('K', 21, 22);
INSERT INTO Tree VALUES ('L', 14, 17);
INSERT INTO Tree VALUES ('M', 15, 16);

