<h1>Approve property <?php echo $this->form->getValue('idProperty') ?></h1>

<form id="approve-property" enctype="application/x-www-form-urlencoded" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
<input type="hidden" name="idProperty" value="<?php echo $this->form->getValue('idProperty') ?>" />
<fieldset>
    <dl>
        <dt>Property Name</dt>
        <dd>
            <?php echo $this->escape($this->propertyRow->shortName) ?>
        </dd> 
        
        <dt>Proposed Location</dt>
        <dd>
            <?php echo $this->locationBreadcrumb($this->locationRow) ?>
        </dd>
        
        <dt>Url Name:</dt>
        <dd>
            <?php echo $this->escape($this->propertyRow->urlName) ?>
        </dd>
        
        <dt>Expiry Date</dt>
        <dd>
            <?php echo $this->prettyDate($this->propertyRow->expiry) ?>
        </dd>
        
        <dd>
            <input type="submit" value="Approve This Property" />
        </dd>
    </dl>
</fieldset>
</form>