<h1>Set the location of property <?php echo $this->form->getValue('idProperty') ?></h1>

<p>The advertiser has request the following suggested location:</p>
<fieldset>
    <dt>Country</dt>
    <dd><?php echo $this->escape($this->propertyContentRowset['country']) ?></dd>

    <dt>Region</dt>
    <dd><?php echo $this->escape($this->propertyContentRowset['region']) ?></dd>

    <dt>Location</dt>
    <dd><?php echo $this->escape($this->propertyContentRowset['location']) ?></dd>
</fieldset>

<p>You should allocate the property to the nearest location available, or create a new location for this property</p>
<?php // var_dump($this->form) ?>
<?php //var_dump($this->hierarchy[19]['children']) ?>

<form enctype="application/x-www-form-urlencoded" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
<input type="hidden" id="idLocation" name="idLocation" value="<?php echo $this->form->getValue('idLocation') ?>" />
<input type="hidden" name="idProperty" value="<?php echo $this->form->getValue('idProperty') ?>" />

<!-- The name attribute is used by tree.serializeArray()  -->
<?php //var_dump($this->locationRowset) ?>
<?php echo $this->locationTree($this->locationRowset) ?>

<?php echo $this->hierarchy ?>

<?php echo $this->displayErrors($this->form->getMessages('idLocation')) ?>
<?php echo $this->displayErrors($this->form->getMessages('idProperty')) ?>
<input type="submit" value="Set Location" />
</form>
