<div class="form">
<h1>Property Completed</h1>
<ul id="property_progress_header">
    <li id="location_orange"></li>
    <li id="content_orange"></li>
    <li id="pictures_orange"></li>
    <li id="rates_orange"></li>
    <li id="availability_orange"></li>
</ul>
<p class="clearfix" />

<p>You have successfully completed all 5 steps and your property has been sent for initial approval.  This usually takes around 24 hours before your listing will appear on the website.<p>

<p><a href="/controlpanel/account/home">Return to my account management home page</a></p>
</div>
