<div class="form">
<h1>Step 4 - Property Rates : <?php echo $this->propertyType($this->propertyRow->idPropertyType) ?> <?php echo $this->escape($this->propertyRow->shortName) ?> - Ref <?php echo $this->propertyRow->idProperty ?></h1>
<ul id="property_progress_header">
    <li id="location_orange"></li>
    <li id="content_orange"></li>
    <li id="pictures_orange"></li>
    <li id="rates_grey"></li>
    <li id="availability_grey"></li>
</ul>
<p class="clearfix" />
<?php echo $this->ratesNotifier($this->propertyRow) ?>
<fieldset>
    <dl>
        <dt><label for="rental_basis">Rental Basis</label></dt>
        <dd><input readonly="Y" name="rentalBasis" value="<?php echo $this->escape($this->rentalBasis($this->rentalBasis)) ?>" /> <?php echo $this->rentalBasisLink ?>
        <a href="<?php echo $this->url(array('module'       => 'controlpanel',
                                             'controller'   => 'rates',
                                             'action'       => 'rental-basis',
                                             'idProperty'   => $this->propertyRow->idProperty,
                                             'digestKey'    => Vfr_DigestKey::generate(array($this->propertyRow->idProperty))), null, true) ?>">[edit]</a></dd>
    </dl>

    <dl>
        <dt><label for="base_currency">Base Currency</label></dt>
        <dd><input readonly="Y" name="base_currency" value="<?php echo $this->escape($this->baseCurrency($this->baseCurrency)) ?>" />  <?php echo $this->baseCurrencyLink ?>
        <a href="<?php echo $this->url(array('module'       => 'controlpanel',
                                             'controller'   => 'rates',
                                             'action'       => 'base-currency',
                                             'idProperty'   => $this->propertyRow->idProperty,
                                             'digestKey'    => Vfr_DigestKey::generate(array($this->propertyRow->idProperty))), null, true) ?>">[edit]</a></dd>
    </dl>
</fieldset>

<form id="step4" enctype="application/x-www-form-urlencoded" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>" />
<input type="hidden" name="idProperty" value="<?php echo $this->form->getValue('idProperty') ?>" />
<input type="hidden" name="digestKey" value="<?php echo $this->form->getValue('digestKey') ?>" />
<table style="width:100%;" cellpadding="0" cellspacing="0" border="1">
<tr>
    <th>Name of Period</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Weekly<br />Rate</th>
    <th>Weekend<br />Nightly<br />Rate</th>
    <th>Midweek<br />Nightly<br />Rate</th>
    <th>Minimum<br />Stay</th>
    <th>Update</th>
    <th>Del</th>
</tr>
<?php
if ($this->ratesRowset) {
    $i = 0;
    foreach ($this->ratesRowset as $row) {
        $line_style = "tbd" . strval($i % 2);
        ?><tr>
            <td class="<?php echo $line_style ?>"><?php echo $row->name ?></td>
            <td class="<?php echo $line_style ?>"><?php echo $this->prettyDate($row->startDate) ?></td>
            <td class="<?php echo $line_style ?>"><?php echo $this->prettyDate($row->endDate) ?></td>
            <td class="<?php echo $line_style ?>"><?php echo $this->rateCurrency($row->weeklyRate, $this->baseCurrency) ?></td>
            <td class="<?php echo $line_style ?>"><?php echo $this->rateCurrency($row->weekendNightlyRate, $this->baseCurrency) ?></td>
            <td class="<?php echo $line_style ?>"><?php echo $this->rateCurrency($row->midweekNightlyRate, $this->baseCurrency) ?></td>
            <td class="<?php echo $line_style ?>"><?php echo $this->minStayDuration($row->minStayDays) ?></td>
            <td class="<?php echo $line_style ?>"><a href="<?php echo $this->url(array('module'     => 'controlpanel',
                                                                                       'controller' => 'rates',
                                                                                       'action'     => 'edit',
                                                                                       'idProperty' => $this->propertyRow->idProperty,
                                                                                       'idRate'     => $row->idRate,
                                                                                       'digestKey'  => Vfr_DigestKey::generate(array(
                                                                                            $this->propertyRow->idProperty,
                                                                                            $row->idRate))
                                                                                       ), null, true) ?>">[edit]</a></td>
            <td class="<?php echo $line_style ?>"><a href="<?php echo $this->url(array('module'     => 'controlpanel',
                                                                                       'controller' => 'rates',
                                                                                       'action'     => 'delete-confirm',
                                                                                       'idProperty' => $this->propertyRow->idProperty,
                                                                                       'idRate'     => $row->idRate,
                                                                                       'digestKey'  => Vfr_DigestKey::generate(array(
                                                                                            $this->propertyRow->idProperty,
                                                                                            $row->idRate))
                                                                                        ), null, true) ?>">[del]</a></td>
        </tr><?php
        $i++;
    }
}
?>
<tr>
    <td><input type="text" name="name" value="<?php echo $this->escape($this->form->getValue('name')) ?>" /></td>
    <td><input id="start" type="text" name="rates[start]" value="<?php echo $this->ratesPicker($this->form->getValue('rates'), 'start') ?>" /></td>
    <td><input id="end" type="text" name="rates[end]" value="<?php echo $this->ratesPicker($this->form->getValue('rates'), 'end') ?>" /></td>
    <td><input id="weeklyRate" type="text" name="rates[weeklyRate]" value="<?php echo $this->ratesPicker($this->form->getValue('rates'), 'weeklyRate') ?>" /></td>
    <td><input id="weekendNightlyRate" type="text" name="rates[weekendNightlyRate]" value="<?php echo $this->ratesPicker($this->form->getValue('rates'), 'weekendNightlyRate') ?>" /></td>
    <td><input id="midweekNightlyRate" type="text" name="rates[midweekNightlyRate]" value="<?php echo $this->ratesPicker($this->form->getValue('rates'), 'midweekNightlyRate') ?>" /></td>
    <td><?php echo $this->formSelect('rates[minStayDays]', $this->ratesPicker($this->form->getValue('rates'), 'minStayDays'), null, $this->form->getElement('minStayDays')->getMultiOptions()) ?></td>
    <td><input type="submit" name="submit" value="submit" /></td>
    <td>&nbsp;</td>
</tr>
</table>
<div>
    <?php echo $this->displayErrors($this->form->getMessages('name')) ?>
    <?php echo $this->displayErrors($this->form->getMessages('rates')) ?>
</div>

</form>
</div>
