<div class="form">
    <h1>Step 3 - Upload your photos</h1>
    <ul id="property_progress_header">
        <li id="location_orange"></li>
        <li id="content_orange"></li>
        <li id="pictures_grey"></li>
        <li id="rates_grey"></li>
        <li id="availability_grey"></li>
    </ul>
    <p class="clearfix" />


    <img alt="" src="<?php echo $this->image ?>" />

    <form accept-charset="utf-8" method="post" action="/controlpanel/image-manager/delete">
        <input type="hidden" name="action" value="remove" />
        <input type="hidden" name="idProperty" value="<?php echo $this->idProperty ?>" />
        <input type="hidden" name="idPhoto" value="<?php echo $this->idPhoto ?>" />
        <input type="hidden" name="digestKey" value="<?php echo $this->digestKey ?>" />
        <input type="submit" name="buttonaction" value="Delete" />
    </form>

    <form accept-charset="utf-8" method="post" action="/controlpanel/image-manager/cancel">
        <input type="hidden" name="idProperty" value="<?php echo $this->idProperty ?>" />
        <input type="hidden" name="idPhoto" value="<?php echo $this->idPhoto ?>" />
        <input type="hidden" name="digestKey" value="<?php echo $this->digestKey ?>" />
        <input type="submit" name="buttonaction" value="Cancel" />
    </form>
</div>