<?php echo $this->paginationControl($this->memberPaginator, 'Sliding', 'pagination.phtml') ?>

<div style="clear:both" />
<table id="list">
    <tr>
        <th><a href="<?php echo $this->url(
            array(
                'order'     => 'idMember',
                'direction' => $this->toggleDirection($this->direction)
            )
        ) ?>">ID</a> <?php echo $this->directionArrow('idMember', $this->order, $this->direction) ?>
        </th>

        <th><a href="<?php echo $this->url(
            array(
                'order'     => 'firstname',
                'direction' =>  $this->toggleDirection($this->direction)
            )
        ) ?>">Firstname</a> <?php echo $this->directionArrow('firstname', $this->order, $this->direction) ?>
        </th>

        <th><a href="<?php echo $this->url(
            array(
                'order'     => 'emailAddress',
                'direction' => $this->toggleDirection($this->direction)
            )
        ) ?>">Email address</a> <?php echo $this->directionArrow('emailAddress', $this->order, $this->direction) ?>
        </th>

        <th><a href="<?php echo $this->url(
            array (
                'order'     => 'added',
                'direction' => $this->toggleDirection($this->direction)
            )
        ) ?>">Joined</a> <?php echo $this->directionArrow('added', $this->order, $this->direction) ?>
        </th>

        <th><a href="<?php echo $this->url(
            array(
                'order'     => 'emailLastConfirmed',
                'direction' => $this->toggleDirection($this->direction)
            )
        ) ?>">Email Last Confirmed</a> <?php echo $this->directionArrow('emailLastConfirmed', $this->order, $this->direction) ?>
        </th>

        <th><a href="<?php echo $this->url(
            array(
                'order'     => 'lastLogin',
                'direction' => $this->toggleDirection($this->direction)
            )
        ) ?>">Last Logged In</a> <?php echo $this->directionArrow('lastLogin', $this->order, $this->direction) ?>
        </th>
    </tr>
    <?php foreach ($this->memberPaginator as $memberRow): ?>
    <tr class="<?php echo $this->cycle(array("odd", "even"))->next() ?>">
        <td><?php echo $memberRow->idMember ?></td>
        <td><?php echo $this->escape($memberRow->firstname) ?></td>
        <td><?php echo $this->escape($memberRow->emailAddress) ?></td>
        <td><?php echo $this->prettyDate($memberRow->added, Vfr_View_Helper_PrettyDate::STYLE_DD_MMM_YY) ?></td>
        <td><?php echo $this->prettyDate($memberRow->emailLastConfirmed, Vfr_View_Helper_PrettyDate::STYLE_DD_MMM_YY_HH_MM_AMPM) ?></td>
        <td><?php echo $this->prettyDate($memberRow->lastlogin, Vfr_View_Helper_PrettyDate::STYLE_DD_MMM_YY_HH_MM_AMPM) ?></td>
    </tr>
    <?php endforeach ?>
</table>
