<?php echo $this->paginationControl($this->advertiserPaginator, 'Sliding', 'pagination.phtml') ?>

<div style="clear:both" />
<table id="list">
    <tr>
        <th><a href="<?php echo $this->url(
            array(
                'order'     => 'idAdvertiser',
                'direction' => $this->toggleDirection($this->direction)
            )
        ) ?>">ID</a> <?php echo $this->directionArrow('idAdvertiser', $this->order, $this->direction) ?>
        </th>

        <th><a href="<?php echo $this->url(
            array(
                'order'     => 'firstname',
                'direction' =>  $this->toggleDirection($this->direction)
            )
        ) ?>">Firstname</a> <?php echo $this->directionArrow('firstname', $this->order, $this->direction) ?>
        </th>

        <th><a href="<?php echo $this->url(
            array(
                'order'     => 'lastname',
                'direction' => $this->toggleDirection($this->direction)
            )
        ) ?>">Lastname</a> <?php echo $this->directionArrow('lastname', $this->order, $this->direction) ?>
        </th>

        <th><a href="<?php echo $this->url(
            array(
                'order'     => 'emailAddress',
                'direction' => $this->toggleDirection($this->direction)
            )
        ) ?>">Email address</a> <?php echo $this->directionArrow('emailAddress', $this->order, $this->direction) ?>
        </th>

        <th>P Set?</th>

        <th><a href="<?php echo $this->url(
            array (
                'order'     => 'added',
                'direction' => $this->toggleDirection($this->direction)
            )
        ) ?>">Joined</a> <?php echo $this->directionArrow('added', $this->order, $this->direction) ?>
        </th>

        <th><a href="<?php echo $this->url(
            array(
                'order'     => 'emailLastConfirmed',
                'direction' => $this->toggleDirection($this->direction)
            )
        ) ?>">Email Last Confirmed</a> <?php echo $this->directionArrow('emailLastConfirmed', $this->order, $this->direction) ?>
        </th>

        <th><a href="<?php echo $this->url(
            array(
                'order'     => 'lastLogin',
                'direction' => $this->toggleDirection($this->direction)
            )
        ) ?>">Last Logged In</a> <?php echo $this->directionArrow('lastLogin', $this->order, $this->direction) ?>
        </th>

        <th>Auto Login</th>
    </tr>
    <?php foreach ($this->advertiserPaginator as $advertiserRow): ?>
    <?php //var_dump($advertiserRow) ?>
    <tr class="<?php echo $this->cycle(array("odd", "even"))->next() ?>">
        <td><?php echo $advertiserRow->idAdvertiser ?></td>
        <td><?php echo $this->escape($advertiserRow->firstname) ?></td>
        <td><?php echo $this->escape($advertiserRow->lastname) ?></td>
        <td><?php echo $this->escape($advertiserRow->emailAddress) ?></td>
        <td><?php echo $this->securePassword($advertiserRow->hash) ?></td>
        <td><?php echo $this->prettyDate(
                $advertiserRow->added,
                Vfr_View_Helper_PrettyDate::STYLE_DD_MMM_YY
        ) ?>
        </td>
        <td><?php echo $this->prettyDate(
            $advertiserRow->emailLastConfirmed,
            Vfr_View_Helper_PrettyDate::STYLE_DD_MMM_YY_HH_MM_AMPM
        ) ?>
        </td>
        <td><?php echo $this->prettyDate(
            $advertiserRow->lastlogin,
            Vfr_View_Helper_PrettyDate::STYLE_DD_MMM_YY_HH_MM_AMPM
        ) ?>
        </td>
        <td><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'auto-login', 'action' => 'login', 'idAdvertiser' => $advertiserRow->idAdvertiser), null, true) ?>">login</a></td>
    </tr>
    <?php // echo $item['idAdvertiser'], $item['iso2char'], $item['username'] ?>
<?php endforeach ?>
</table>
