<h1>Advertisers :: List Advertisers</h1>
<?php echo $this->paginationControl($this->advertiserPaginator, 'Sliding', 'pagination.phtml') ?>

<div style="clear:both" />
<table id="advertiser-list">
	<tr>
		<th><a href="<?php echo $this->url(
			array (
				'sort'	     => 'idAdvertiser',
				'direction'  => $this->toggleDirection($this->direction)
			)) ?>">ID</a> <?php echo $this->directionArrow('idAdvertiser', $this->sort, $this->direction) ?></td>
			
		<th><a href="<?php echo $this->url(
			array (
				'sort'       => 'firstname',
				'direction'  =>  $this->toggleDirection($this->direction)
			)) ?>">Firstname</a> <?php echo $this->directionArrow('firstname', $this->sort, $this->direction) ?></th>
		<th><a href="<?php echo $this->url(
			array (
				'sort' => 'lastname',
				'direction' => $this->toggleDirection($this->direction)
		    )) ?>">Lastname</a> <?php echo $this->directionArrow('lastname', $this->sort, $this->direction) ?></th>
		<th><a href="<?php echo $this->url(
			array (
				'sort' => 'emailAddress',
				'direction' => $this->toggleDirection($this->direction)
		    )) ?>">Email address</a> <?php echo $this->directionArrow('emailAddress', $this->sort, $this->direction) ?></th>
		<th>Secure P</th>
		<th><a href="<?php echo $this->url(
			array (
		        'sort' => 'passwd',
				'direction' => $this->toggleDirection($this->direction)
		    )) ?>">Password</a> <?php echo $this->directionArrow('passwd', $this->sort, $this->direction) ?></th>
		<th><a href="<?php echo $this->url(
			array (
				'sort' => 'added',
				'direction' => $this->toggleDirection($this->direction)
			)) ?>">Joined</a> <?php echo $this->directionArrow('added', $this->sort, $this->direction) ?></th>
		<th><a href="<?php echo $this->url(
			array (
				'sort' => 'lastLogin',
				'direction' => $this->toggleDirection($this->direction)
			)) ?>">Last Logged In</a> <?php echo $this->directionArrow('lastLogin', $this->sort, $this->direction) ?></th>
	</tr>
<?php foreach ($this->advertiserPaginator as $advertiserRow): ?>
<?php //var_dump($advertiserRow) ?>
	<tr class="<?php echo $this->cycle(array("odd", "even"))->next() ?>">
		<td><?php echo $advertiserRow->idAdvertiser ?></td>
		<td><?php echo $this->escape($advertiserRow->firstname) ?></td>
		<td><?php echo $this->escape($advertiserRow->lastname) ?></td>
		<td><?php echo $this->escape($advertiserRow->emailAddress) ?></td>
		<td><?php echo $this->securePassword($advertiserRow->hash) ?></td>
		<td><?php echo $this->escape($advertiserRow->passwd) ?></td>
		<td><?php echo $this->prettyDate($advertiserRow->added, Vfr_View_Helper_PrettyDate::STYLE_DD_MMM_YY) ?></td>
		<td><?php echo $this->prettyDate($advertiserRow->lastlogin, Vfr_View_Helper_PrettyDate::STYLE_DD_MMM_YY_HH_MM_AMPM) ?></td>
	</tr>
	<?php // echo $item['idAdvertiser'], $item['iso2char'], $item['username'] ?>
<?php endforeach ?>
</table>