<h1>Vfr Core</h1>
<h2>Availability Calendar</h2>
<table class="system-versions-table">
    <tr>
        <td class="component-name">Vfr_Availability_Calendar_ImagePng</td>
        <td class="description">Generates the availability PNG images</td>
        <td class="version-number"><?php echo $this->versions['Vfr_Availability_Calendar_ImagePng'] ?></td>
    </tr>
</table>

<h2>Encryption and Hashing</h2>
<table class="system-versions-table">
    <tr>
        <td class="component-name">Vfr_BlowfishHasher</td>
        <td class="description">Hashes passwords for DB storage</td>
        <td class="version-number"><?php echo $this->versions['Vfr_BlowfishHasher'] ?></td>
    </tr>
</table>

<h2>Encryption and Hashing</h2>
<table class="system-versions-table">
    <tr>
        <td class="component-name">Vfr_Property_Converter</td>
        <td class="description">Converts property ids to directory structures</td>
        <td class="version-number"><?php echo $this->versions['Vfr_Property_Converter'] ?></td>
    </tr>
</table>



<h2>Validators</h2>
<table class="system-versions-table">
    <tr>
        <td class="component-name">Vfr_Validate_AvailabilityRange</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_Validate_AvailabilityRange'] ?></td>
    </tr>
    
    <tr>
        <td class="component-name">Vft_Validate_EmailCheck</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_Validate_EmailCheck'] ?></td>
    </tr>
    
    <tr>
        <td class="component-name">Vfr_Validate_PasswordConfirmation</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_Validate_PasswordConfirmation'] ?></td>
    </tr>
    
    <tr>
        <td class="component-name">Vfr_Validate_PropertyUrl</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_Validate_PropertyUrl'] ?></td>
    </tr>
    
    <tr>
        <td class="component-name">Vfr_Validate_Rates_Range</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_Validate_RatesRange'] ?></td>
    </tr>
    
    <tr>
        <td class="component-name">Vfr_Validate_UniqueAdvertiserEmail</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_Validate_UniqueAdvertiserEmail'] ?></td>
    </tr>
</table>

<h2>Validators</h2>
<table class="system-versions-table">
    <tr>
        <td class="component-name">Vfr_View_Helper_AdvertiserControlPanelStatus</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_AdvertiserControlPanelStatus'] ?></td>
    </tr>
    
    <tr>
        <td class="component-name">Vfr_View_Helper_AspectRatio</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_AspectRatio'] ?></td>
    </tr>
    
    <tr>
        <td class="component-name">Vfr_View_Helper_AvailabilityNotifier</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_AvailabilityNotifier'] ?></td>
    </tr>
    
    <tr>
        <td class="component-name">Vfr_View_Helper_AvailabilityPicker</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_AvailabilityPicker'] ?></td>
    </tr>
    
    <tr>
        <td class="component-name">Vfr_View_Helper_BaseCurrency</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_BaseCurrency'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_Bytes</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_Bytes'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_DisplayErrors</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_DisplayErrors'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_FormatCurrency</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_FormatCurrency'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_HolidayType</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_HolidayType'] ?></td>
    </tr>
    
    <tr>
        <td class="component-name">Vfr_View_Helper_ImageConfirmDeleteButton</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_ImageConfirmDeleteButton'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_ImageMoveButtons</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_ImageMoveButtons'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_ImageUploadNotifier</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_ImageUploadNotifier'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_LocationBreadcrumb</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_LocationBreadcrumb'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_MinStayDuration</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_MinStayDuration'] ?></td>
    </tr>
    
    <tr>
        <td class="component-name">Vfr_View_Helper_Photo</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_Photo'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_Photo</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_Photo'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_PrettyDate</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_PrettyDate'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_PropertyTinyThumb</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_PropertyTinyThumb'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_PropertyType</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_PropertyType'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_RateCurrency</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_RateCurrency'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_RatesNotifier</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_RatesNotifier'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_RatesPicker</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_RatesPicker'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_RentalBasis</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_RentalBasis'] ?></td>
    </tr>
    
    
    <tr>
        <td class="component-name">Vfr_View_Helper_SummaryBar</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_SummaryBar'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_TinyThumb</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_TinyThumb'] ?></td>
    </tr>
    <tr>
        <td class="component-name">Vfr_View_Helper_WebsiteUrl</td>
        <td class="description">tbd</td>
        <td class="version-number"><?php echo $this->versions['Vfr_View_Helper_WebsiteUrl'] ?></td>
    </tr>
</table>


<h1>Frontend</h1>
<h2>Action Controllers</h2>
<table class="system-versions-table">    
    <tr>
        <td class="component-name">AdvertiserAccountController</td>
        <td class="description">Main control panel page after an advertiser logs in</td>
        <td class="version-number"><?php //echo $this->versions['AdvertiserAccountController'] ?></td>
    </tr>
</table>
<h2>View Helpers</h2>

<h1>Common</h1>
<h2>Models and Resources</h2>

<h1>Admin</h1>
<h2>Action Controllers</h2>

<h2>View Helpers</h2>

<h1>API</h1>
<h2>Action Controllers</h2>