CREATE TABLE IF NOT EXISTS Calendars (
    idCalendar int(10) unsigned NOT NULL AUTO_INCREMENT,
    idProperty int(10) unsigned NOT NULL,
    calendarName varchar(255) NOT NULL,
    visible int(1) NOT NULL DEFAULT '1',
    vLanguage varchar(32) NOT NULL DEFAULT 'en_EN',
    vDuration int(2) unsigned NOT NULL DEFAULT '12',
    vStartYear int(4) unsigned NOT NULL DEFAULT '99',
    vStartMonth int(2) unsigned NOT NULL DEFAULT '99',
    vColumns int(1) unsigned NOT NULL DEFAULT '4',
    vSlope int(1) NOT NULL DEFAULT '1',
    vBoundary int(1) NOT NULL DEFAULT '0',
    vBookedColour char(6) NOT NULL DEFAULT 'FF6600',
    vProvBookedColour char(6) NOT NULL DEFAULT 'F66606',
    vAvailableColour char(6) NOT NULL DEFAULT '99CC99',
    vUnavailableColour char(6) NOT NULL DEFAULT 'CCCCCC',
    vTitleHeightPixels int(2) unsigned NOT NULL DEFAULT '15',
    vDayCellWidthPixels int(2) unsigned NOT NULL DEFAULT '14',
    vDayCellHeightPixels int(2) unsigned NOT NULL DEFAULT '13',
    vDayNameColour char(6) NOT NULL DEFAULT 'CC0000',
    vTableBorderColour char(6) NOT NULL DEFAULT '336699',
    vKeyOn int(1) NOT NULL DEFAULT '1',
    vNumKeys int(1) unsigned NOT NULL DEFAULT '3',
    vHorizontalGapPixels int(2) unsigned NOT NULL DEFAULT '4',
    vVerticalGapPixels int(2) unsigned NOT NULL DEFAULT '2',
    vWeekStartDay int(2) unsigned NOT NULL DEFAULT '0',
    rentalBasis char(2) CHARACTER SET ascii NOT NULL DEFAULT 'PR',
    currencyCode char(3) CHARACTER SET ascii NOT NULL DEFAULT 'GBP',
    added datetime NOT NULL,
    updated datetime NOT NULL,
    PRIMARY KEY (idCalendar),
    KEY (idProperty),
    KEY added (added),
    KEY updated (updated),
    KEY visible (visible),
    KEY rentalBasis (rentalBasis),
    KEY currencyCode (currencyCode),
    CONSTRAINT calendars_ibfk_1 FOREIGN KEY (idProperty) REFERENCES Properties (idProperty) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT calendars_ibfk_2 FOREIGN KEY (currencyCode) REFERENCES Currencies (iso3char) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
