CREATE TABLE IF NOT EXISTS Destinations (
    idDestination int(10) unsigned NOT NULL AUTO_INCREMENT,
    idRegion int(10) unsigned NOT NULL,
    name varchar(255) NOT NULL,
    displayPriority int(10) unsigned NOT NULL,
    prefix varchar(255) DEFAULT NULL,
    postfix varchar(255) DEFAULT NULL,
    visible int(1) NOT NULL DEFAULT '1',
    added datetime NOT NULL,
    updated datetime NOT NULL,
	lastModifiedBy varchar(32) CHARACTER SET ascii NOT NULL DEFAULT 'system',
    PRIMARY KEY (idDestination),
    UNIQUE KEY name (idRegion, name),
    KEY added (added),
    KEY updated (updated),
    KEY visible (visible),
    KEY displayPriority (displayPriority),
    KEY lastModifiedBy (lastModifiedBy),
    KEY idRegion (idRegion),
    CONSTRAINT destinations_ibfk_1 FOREIGN KEY (idRegion) REFERENCES Regions (idRegion) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
