CREATE TABLE IF NOT EXISTS FastLookups (
    idFastLookup int(10) unsigned NOT NULL AUTO_INCREMENT,
    url varchar(255) CHARACTER SET ascii NOT NULL,
    idProperty int(10) unsigned NOT NULL,
    idCountry int(10) unsigned NOT NULL,
    idRegion int(10) unsigned NOT NULL,
    idDestination int(10) unsigned NOT NULL,
    totalVisible int(10) unsigned NULL,
    total int(10) unsigned NULL,
    countryName varchar(255) DEFAULT NULL,
    regionName varchar(255) DEFAULT NULL,
    destinationName varchar(255) DEFAULT NULL,
    added datetime NOT NULL,
    updated datetime NOT NULL,
    PRIMARY KEY (idFastlookup),
	UNIQUE KEY (url),
    KEY idProperty (idProperty),
    KEY idCountry (idCountry),
    KEY idRegion (idRegion),
    KEY idDestination (idDestination),
    KEY totalVisible (totalVisible),
    KEY total (total),
    KEY added (added),
    KEY updated (updated),
    CONSTRAINT fastlookups_ibfk_1 FOREIGN KEY (idProperty) REFERENCES Properties (idProperty) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fastlookups_ibfk_2 FOREIGN KEY (idCountry) REFERENCES Countries (idCountry) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fastlookups_ibfk_3 FOREIGN KEY (idRegion) REFERENCES Regions (idRegion) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fastlookups_ibfk_4 FOREIGN KEY (idDestination) REFERENCES Destinations (idDestination) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
