CREATE TABLE IF NOT EXISTS InvoiceItems (
    idInvoiceItem int(10) unsigned NOT NULL AUTO_INCREMENT,
    idInvoice int(8) unsigned zerofill NOT NULL,
    idWebProduct int(10) unsigned DEFAULT NULL,
    idWebService int(10) unsigned DEFAULT NULL,
    qty int(10) unsigned NOT NULL DEFAULT '1',
    unitAmount decimal(8,2) NOT NULL DEFAULT '0.00',
    description text NOT NULL,
    startDate date DEFAULT NULL,
    expiryDate date DEFAULT NULL,
    repeats varchar(32) CHARACTER SET ascii DEFAULT NULL,
    lineTotal decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT 'line total amount',
    added datetime NOT NULL,
    updated datetime NOT NULL,
    PRIMARY KEY (idInvoiceItem),
    KEY idInvoice (idInvoice),
    KEY idWebProduct (idWebProduct),
    KEY idWebService (idWebService),
    KEY qty (qty),
    KEY startDate (startDate),
    KEY expiryDate (expiryDate),
    KEY repeats (repeats),
    KEY added (added),
    KEY updated (updated),
    CONSTRAINT idInvoice2_ibfk FOREIGN KEY (idInvoice) REFERENCES Invoices (idInvoice) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT idWebProduct_ibfk FOREIGN KEY (idWebProduct) REFERENCES WebProducts (idWebProduct) ON UPDATE CASCADE,
    CONSTRAINT idWebService_ibfk FOREIGN KEY (idWebService) REFERENCES WebServices (idWebService) ON UPDATE CASCADE;
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
