CREATE TABLE IF NOT EXISTS Members (
    idMember int(10) unsigned NOT NULL AUTO_INCREMENT,
    emailAddress varchar(255) CHARACTER SET ascii NOT NULL,
    changeEmailAddress varchar(255) CHARACTER SET ascii DEFAULT NULL,
    hash varchar(60) CHARACTER SET ascii DEFAULT NULL,
    firstname varchar(255),
    lastname varchar(255),
    added datetime NOT NULL,
    updated datetime NOT NULL,
    lastlogin datetime NULL,
    emailLastConfirmed varchar(255) CHARACTER SET ascii DEFAULT NULL,
    lastModifiedBy varchar(32) NOT NULL DEFAULT 'system',
    PRIMARY KEY (idMember),
    UNIQUE emailAddress (emailAddress),
    KEY hash (hash),
    KEY firstname (firstname),
    KEY lastname (lastname),
    KEY lastLogin (lastLogin),
    KEY changeEmailAddress (changeEmailAddress),
    KEY emailLastConfirmed (emailLastConfirmed),
    KEY added (added),
    KEY updated (updated),
    KEY lastModifiedBy (lastModifiedBy)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
