CREATE TABLE IF NOT EXISTS MessageThreads (
    idMessageThread int(10) unsigned NOT NULL AUTO_INCREMENT,
    idMember int(10) unsigned DEFAULT NULL,
    idAdvertiser int(10) unsigned DEFAULT NULL,
    summary varchar(64) NOT NULL DEFAULT '',
    storeMember enum('INBOX','ARCHIVED') CHARACTER SET ascii NOT NULL,
    storeAdvertiser enum('INBOX','ARCHIVED') CHARACTER SET ascii NOT NULL,
    readMember int(10) unsigned NOT NULL DEFAULT '0',
    readAdvertiser int(10) unsigned NOT NULL,
    messageCount int(10) unsigned NOT NULL DEFAULT '0',
    lastMessage datetime NOT NULL,
    updated datetime NOT NULL,
    PRIMARY KEY (idMessageThread),
    UNIQUE KEY MemAdv (idMember, idAdvertiser),
    KEY stored (storeMember),
    KEY idAdvertiser (idAdvertiser),
    KEY idMember (idMember),
    KEY lastMessage (lastMessage),
    KEY storeAdvertiser (storeAdvertiser),
    KEY readMember (readMember,readAdvertiser),
    KEY updated (updated),
    CONSTRAINT messagethreads_ibfk_1 FOREIGN KEY (idAdvertiser) REFERENCES Advertisers (idAdvertiser) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT messagethreads_ibfk_2 FOREIGN KEY (idMember) REFERENCES Members (idMember) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
