CREATE TABLE IF NOT EXISTS MessageThreads (
    idMessageThread int(10) unsigned NOT NULL AUTO_INCREMENT,
    idMember int(10) unsigned NOT NULL,
    idAdvertiser int(10) unsigned NOT NULL,
    direction int(1) unsigned NOT NULL DEFAULT '2' COMMENT '1 user, 2 advertiser',
    threadVisibleUser int(1) unsigned NOT NULL DEFAULT '1',
    threadVisibleAdvertiser int(1) unsigned NOT NULL DEFAULT '1',
    turnToReply int(1) unsigned NOT NULL DEFAULT '2' COMMENT '1 user, 2 advertiser',
    subject varchar(255) NOT NULL,
    summary varchar(64) NOT NULL,
    sent datetime NOT NULL,
    PRIMARY KEY (idMessageThread),
    KEY direction (direction),
    KEY sent (sent),
    KEY idMember (idMember),
    KEY idAdvertiser (idAdvertiser),
    KEY threadVisibleUser (threadVisibleUser),
    KEY threadVisibleAdvertiser (threadVisibleAdvertiser),
    CONSTRAINT message_threads_ibfk_1 FOREIGN KEY (idMember) REFERENCES Members (idMember) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT message_threads_ibfk_2 FOREIGN KEY (idAdvertiser) REFERENCES Advertisers (idAdvertiser) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;