CREATE TABLE IF NOT EXISTS Photos (
    idPhoto int(10) unsigned NOT NULL AUTO_INCREMENT,
    approved int(1) unsigned NOT NULL,
    idProperty int(10) unsigned NOT NULL,
    displayPriority int(10) unsigned NOT NULL DEFAULT '1',
    originalFilename varchar(255) NOT NULL,
    fileType char(3) CHARACTER SET ascii NOT NULL DEFAULT 'jpg',
    widthPixels int(10) unsigned NOT NULL,
    heightPixels int(10) unsigned NOT NULL,
    sizeK int(10) unsigned NOT NULL,
    caption text NOT NULL,
    visible int(1) NOT NULL DEFAULT '1',
    added datetime NOT NULL,
    updated datetime NOT NULL,
    lastModifiedBy varchar(32) CHARACTER SET ascii NOT NULL DEFAULT 'system',
    PRIMARY KEY (idPhoto),
    KEY visible (visible),
    KEY added (added),
    KEY updated (updated),
    KEY approved (approved),
    KEY displayPriority (displayPriority),
    KEY lastModifiedBy (lastModifiedBy),
    KEY idProperty (idProperty),
    CONSTRAINT photos_ibfk_1 FOREIGN KEY (approved) REFERENCES PhotoApprovals (idPhotoApproval) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT photos_ibfk_2 FOREIGN KEY (idProperty) REFERENCES Properties (idProperty) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
