CREATE TABLE IF NOT EXISTS Properties (
    idProperty int(10) unsigned NOT NULL AUTO_INCREMENT,
    idPropertyType int(10) unsigned NOT NULL,
    idAdvertiser int(10) unsigned NOT NULL,
    idCountry int(10) unsigned NOT NULL,
    idRegion int(10) unsigned NOT NULL,
    idDestination int(10) unsigned NOT NULL,
    urlName varchar(255) CHARACTER SET ascii NOT NULL,
    shortName varchar(255) NOT NULL,
    locationUrl varchar(255) CHARACTER SET ascii NOT NULL,
    numBeds int(10) unsigned NULL,
    numSleeps int(10) unsigned NULL,
    approved int(1) NOT NULL DEFAULT '0',
    visible int(1) NOT NULL,
    expiry date DEFAULT NULL,
    featureMask int(10) unsigned NOT NULL DEFAULT '0',
    featureExpiry date DEFAULT NULL,
    featurePriority int(11) NOT NULL DEFAULT '1',
    golfHoliday int(1) NOT NULL DEFAULT '0',
    skiingHoliday int(1) NOT NULL DEFAULT '0',
    accessHoliday int(1) NOT NULL DEFAULT '0',
    emailAddress varchar(255) CHARACTER SET ascii NOT NULL,
    photoLimit int(10) unsigned NOT NULL DEFAULT '4',
    added datetime NOT NULL,
    updated datetime NOT NULL,
    awaitingApproval int(1) NOT NULL DEFAULT '0',
    changesMade int(1) NOT NULL DEFAULT '0',
    status int(8) unsigned DEFAULT NULL,
    lastModifiedBy varchar(32) NOT NULL DEFAULT 'system',
    PRIMARY KEY (idProperty),
    UNIQUE KEY urlName (urlName),
    KEY approved (approved),
    KEY visible (visible),
    KEY expiry (expiry),
    KEY added (added),
    KEY updated (updated),
    KEY status (status),
    KEY idCountry (idCountry),
    KEY idRegion (idRegion),
    KEY idDestination (idDestination),
    KEY golfHoliday (golfHoliday),
    KEY skiingHoliday (skiingHoliday),
    KEY numBeds (numBeds),
    KEY accessHoliday (accessHoliday),
    KEY numSleeps (numSleeps),
    KEY featureExpiry (featureExpiry),
    KEY lastModfiedBy (lastModifiedBy),
    KEY locationUrl (locationUrl),
    KEY idAdvertiser (idAdvertiser),
    KEY idPropertyType (idPropertyType),
    KEY featurePriority (featurePriority),
    KEY awaitingApproval (awaitingApproval),
    KEY changesMade (changesMade),
    CONSTRAINT properties_ibfk_1 FOREIGN KEY (idAdvertiser) REFERENCES Advertisers (idAdvertiser) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT properties_ibfk_2 FOREIGN KEY (idCountry) REFERENCES Countries (idCountry) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT properties_ibfk_3 FOREIGN KEY (idRegion) REFERENCES Regions (idRegion) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT properties_ibfk_4 FOREIGN KEY (idDestination) REFERENCES Destinations (idDestination) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT properties_ibfk_5 FOREIGN KEY (idPropertyType) REFERENCES PropertyTypes (idPropertyType) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;