CREATE TABLE IF NOT EXISTS Properties (
    idProperty int(10) unsigned NOT NULL AUTO_INCREMENT,
    idPropertyType int(10) unsigned NOT NULL,
    idAdvertiser int(10) unsigned NOT NULL,
    idHolidayType int(10) unsigned NOT NULL,
    idLocation int(10) unsigned NULL,
    urlName varchar(255) CHARACTER SET ascii NOT NULL,
    shortName varchar(255) NOT NULL,
    locationUrl varchar(255) CHARACTER SET ascii NOT NULL,
    numBeds int(10) unsigned NULL,
    numSleeps int(10) unsigned NULL,
    approved int(1) NOT NULL DEFAULT '0',
    visible int(1) NOT NULL,
    expiry date DEFAULT NULL,
    emailAddress varchar(255) CHARACTER SET ascii NOT NULL,
    photoLimit int(10) unsigned NOT NULL DEFAULT '4',
    added datetime NOT NULL,
    updated datetime NOT NULL,
    awaitingApproval int(1) NOT NULL DEFAULT '0',
    changesMade int(1) NOT NULL DEFAULT '0',
    status int(8) unsigned DEFAULT NULL,
    checksumMaster char(40) CHARACTER SET ascii DEFAULT NULL,
    checksumUpdate char(40) CHARACTER SET ascii DEFAULT NULL,
    lastModifiedBy varchar(32) NOT NULL DEFAULT 'system',
    PRIMARY KEY (idProperty),
    UNIQUE KEY urlName (urlName),
    KEY approved (approved),
    KEY visible (visible),
    KEY expiry (expiry),
    KEY added (added),
    KEY updated (updated),
    KEY status (status),
    KEY checksumMaster (checksumMaster),
    KEY checksumUpdate (checksumUpdate),
    KEY idHolidayType (idHolidayType),
    KEY idLocation (idLocation),
    KEY numBeds (numBeds),
    KEY numSleeps (numSleeps),
    KEY lastModfiedBy (lastModifiedBy),
    KEY locationUrl (locationUrl),
    KEY idAdvertiser (idAdvertiser),
    KEY idPropertyType (idPropertyType),
    KEY awaitingApproval (awaitingApproval),
    KEY changesMade (changesMade),
    CONSTRAINT properties_ibfk_1 FOREIGN KEY (idAdvertiser) REFERENCES Advertisers (idAdvertiser) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT properties_ibfk_2 FOREIGN KEY (idLocation) REFERENCES Locations (idLocation) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT properties_ibfk_3 FOREIGN KEY (idPropertyType) REFERENCES PropertyTypes (idPropertyType) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;