CREATE TABLE IF NOT EXISTS Regions (
    idRegion int(10) unsigned NOT NULL AUTO_INCREMENT,
    idCountry int(10) unsigned NOT NULL,
    name varchar(255) NOT NULL,
    displayPriority int(10) unsigned NOT NULL,
    prefix varchar(255) DEFAULT NULL,
    postfix varchar(255) DEFAULT NULL,
    visible int(1) NOT NULL DEFAULT '1',
    added datetime NOT NULL,
    updated datetime NOT NULL,
	lastModifiedBy varchar(32) CHARACTER SET ascii NOT NULL DEFAULT 'system',
    PRIMARY KEY (idRegion),
    UNIQUE KEY name (idCountry, name),
    KEY added (added),
    KEY updated (updated),
    KEY visible (visible),
    KEY displayPriority (displayPriority),
    KEY lastModifiedBy (lastModifiedBy),
    KEY idCountry (idCountry),
    CONSTRAINT regions_ibfk_1 FOREIGN KEY (idCountry) REFERENCES Countries (idCountry) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
