CREATE TABLE IF NOT EXISTS RemoteAccess (
    idRemoteAccess int(8) unsigned NOT NULL AUTO_INCREMENT,
    idAdvertiser int(10) unsigned NOT NULL,
    idProperty int(10) unsigned NOT NULL,
    idRemoteService int(4) unsigned NOT NULL,
    userfield int(4) unsigned zerofill NOT NULL,
    domain varchar(255) CHARACTER SET ascii NOT NULL,
    apikeymd5 char(32) CHARACTER SET ascii NOT NULL,
    expires date NOT NULL,
    suspended int(1) unsigned NOT NULL DEFAULT '0',
    added datetime NOT NULL,
    updated datetime NOT NULL,
    PRIMARY KEY (idRemoteAccess),
    UNIQUE KEY apikeymd5 (apikeymd5),
    KEY added (added),
    KEY updated (updated),
    KEY passwdmd5 (apikeymd5),
    KEY expires (expires),
    KEY suspended (suspended),
    KEY userfield (userfield),
    KEY domain (domain),
    KEY idProperty (idProperty),
    KEY idAdvertiser (idAdvertiser),
    KEY idRemoteService (idRemoteService),
    CONSTRAINT remote_access_ibfk_1 FOREIGN KEY (idAdvertiser) REFERENCES Advertisers (idAdvertiser) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT remote_access_ibfk_2 FOREIGN KEY (idProperty) REFERENCES Properties (idProperty) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT remote_access_ibfk_3 FOREIGN KEY (idRemoteService) REFERENCES RemoteServices (idRemoteService) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
