<?php //echo $this->messageObj->getSentBy() ?>

<div class="inbox-message">
    <div class="inbox-message-image">
        <img src="https://secure.gravatar.com/avatar/02b5939ce50939e58dac8090b9aa5236?s=80&d=wavatar&r=pg">
    </div>

    <div class="inbox-message-body">
        <div class="inbox-message-body-header"><?php echo $this->messageName($this->messageObj->getSentBy(), $this->idMember, $this->idAdvertiser) ?><span><?php echo $this->prettyDate($this->messageObj->getAdded(), Vfr_View_Helper_PrettyDate::STYLE_DD_MMM_YY_HH_MM_AMPM) ?></span></div>
        <div class="inbox-message-body-text">
        <p><?php echo $this->escape($this->purifier->purify($this->messageObj->getBody())) ?></p>
        </div>

        <?php //var_dump($this->messageObj) ?>
    </div>
    <div style="clear: both"></div>
</div>
