Hi <?php echo $this->firstname ?>,

Your property id (<?php echo $this->idProperty ?>) with name <?php echo $this->shortName ?> has been approved.

To view your property profile page directly, with the same perspective as your customers use the following link:

<?php echo $this->nonSecureUrl ?>/<?php echo $this->locationUrl ?>/<?php echo $this->urlName ?>


If clicking doesn't seem to work, you can copy and paste the link into your browser's address window, or retype it there.

You can go back to edit the content using your control panel, by using the link below:

<?php echo $this->nonSecureUrl ?>/controlpanel/authentication/login


The HolidayPropertyWorldwide.com Team

