Hi <?php echo $this->firstname ?>,

To change your account to use your new address, please follow this link
<?php echo $this->secureUrl ?>/controlpanel/change-email-address/confirm/token/<?php echo $this->token ?>

(If clicking on the link doesn't work, try copying and pasting it into your browser.)

If you did not enter this address as your contact email, please disregard this message.

Thanks,
The HolidayPropertyWorldwide.com Team
