Greetings from HolidayPropertyWorldwide.com

We received a request to reset the advertiser account password associated with this email address. If you made this request, please follow the instructions below.

If you did not request to have your password reset you can safely ignore this email. Rest assured your advertiser account is safe.

Click the link below to go to reset your password using our secure server:

<?php echo $this->secureUrl ?>/controlpanel/password-reset/reset/token/<?php echo $this->token ?>

If clicking doesn't seem to work, you can copy and paste the link into your browser's address window, or retype it there. Once you have returned to HolidayPropertyWorldwide.com, we will give instructions for resetting your password.

HolidayPropertyWorldwide.com will never email you to ask you to disclose or verify any passwords, credit card, or bank account numbers. If you receive a suspicious email with a link to update your account information, do not click on any links within. Instead, report the email to us for investigation.


The HolidayPropertyWorldwide.com Team
