Property ID: <?php echo $this->idProperty ?> has had a new photo uploaded (Photo ID=<?php echo $this->idPhoto ?>)

The details of the property are as follows:

Original Filename: <?php echo $this->originalFilename ?>
Image Type: <?php echo $this->fileType ?>
Width x Height (pixels): <?php echo $this->widthPixels ?> x <?php echo $this->heightPixels ?>
Size: <?php echo $this->sizeK ?>
Caption: <?php echo $this->caption ?>

You can reach the Administration Control Panel using the link below:
<?php echo $this->secureUrl ?>/admin

HolidayPropertyWorldwide.com Automated Mailer


