Dear <?php echo $this->firstname ?> <?php echo $this->lastname ?>,

To complete your account application, please click the link below:

<?php echo $this->secureUrl ?>/advertiser-email-confirmation/confirm/<?php echo $this->token ?>

If clicking doesn't seem to work, you can copy and paste the link into your browser's address window, or retype it there. Once you have returned to HolidayPropertyWorldwide.com, your account will be active and you can add your property.

If you are not <?php echo $this->firstname ?> <?php echo $this->lastname ?>, it is possible that somebody mistyped their email address during the registration process, and you can safely delete this email.




