A new advertiser has joined the website.

There details are as follows:
Advertiser ID: <?php echo $this->idAdvertiser ?>
Firstname: <?php echo $this->firstname ?>
Lastname: <?php echo $this->lastname ?>
Email address: <?php echo $this->emailAddress ?>
Joined: <?php echo $this->added ?>

You can reach the Administration Control Panel using the link below:
<?php echo $this->secureUrl ?>/admin

HolidayPropertyWorldwide.com Automated Mailer

