<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>YUI2 - TreeView Test</title>
    
    <!-- Required CSS -->
    <link type="text/css" rel="stylesheet" href="http://yui.yahooapis.com/2.8.2r1/build/treeview/assets/skins/sam/treeview.css">
    
    <!-- Optional CSS for for date editing with Calendar-->
    <link type="text/css" rel="stylesheet" href="http://yui.yahooapis.com/2.8.2r1/build/calendar/assets/skins/sam/calendar.css">

    <!-- Dependency source file --> 
    <script src="http://yui.yahooapis.com/2.8.2r1/build/yahoo-dom-event/yahoo-dom-event.js" ></script>
    
    <!-- Optional dependency source file --> 
    <script src="http://yui.yahooapis.com/2.8.2r1/build/animation/animation-min.js" type="text/javascript"></script>
    
    <!-- Optional dependency source file for date editing with Calendar--> 
    <script src="http://yui.yahooapis.com/2.8.2r1/build/calendar/calendar-min.js" ></script>
    
    <!-- Optional dependency source file to decode contents of yuiConfig markup attribute--> 
    <script src="http://yui.yahooapis.com/2.8.2r1/build/json/json-min.js" ></script>

    <!-- TreeView source file --> 
    <script src="http://yui.yahooapis.com/2.8.2r1/build/treeview/treeview-min.js" ></script>
</head>
<body class="yui-skin-sam">
    <div id="treeDiv1">
    <ul>
        <li class="expanded">List 0
            <ul>
                <li class="expanded">List 0-0
                    <ul>
                        <li>item 0-0-0</li>
                        <li><a target="_new" href="#" title="go elsewhere">elsewhere</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li>List 1
            <ul>
                <li>List 1-0
                    <ul>
                        <li yuiConfig='{"type":"DateNode","editable":true}'>02/01/2009</li>
                        <li><span>item <strong>1-1-0</strong></span></li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</div>
<script type="text/javascript">
    var tree;
    
    function treeInit() {
        alert("Click me to continue");
        tree = new YAHOO.widget.TreeView("treeDiv1");
        tree.render();
    }
        
    treeInit();
</script>
</body>
</html>