<?php if ($this->idPropertyList) : ?>
<style>
#delete-from-favourites {
	height: 11px;
	width: 11px;
	background-image: url('/images/frontend/inbox/cross.png');
	background-repeat: no-repeat;
}

.cross {
    background-image: url('/images/frontend/inbox/cross.png');
    background-repeat: no-repeat;
    background-position: 0 0;
    display: inline-block;
    width: 11px;
    height: 11px;
    cursor: pointer;
}
.cross:hover {
    background-position: 0 -24px;
}
.cross:active {
    background-position: 0 -36px;
}

</style>
<table>
<?php foreach ($this->idPropertyList as $idProperty) : ?>
<?php echo $this->partial('dashboard/partials/member-favourite.phtml',array(
                'photoRow'   => $this->photoLookup[$idProperty],
                'propertyRow' => $this->propertyLookup[$idProperty],
                'propertyContentRow' => $this->propertyContentLookup[$idProperty],
                'idProperty' => $idProperty)
) ?>
<?php endforeach ?>
</table>
<?php endif ?>