<div style="clear:both" />
<table id="list">
    <tr>
        <!--<th>Location Name</th>-->
        <th>URL</th>
        <th>Language</th>
        <th>Field Tag</th>
        <th>Priority</th>
        <th>Content</th>
        <th>ACTION</th>
    </tr>
    <?php
        $current = null;
        $topEntry = true;
    ?>
    <?php foreach ($this->locationContentRowset as $locationContentRow) : ?>
    <?php //var_dump($locationContentRow) ?>
    <?php
    if ($current != $locationContentRow->idLocation) {
        $color = $this->cycle(array("odd", "even"))->next();
        $current = $locationContentRow->idLocation;
        $topEntry = true;
    } else {
        if ($topEntry)
            $topEntry = false;
    }
    ?>
    <tr class="<?php echo $color ?>">
        <!--<td><?php //echo $this->escape($locationContentRow->name) ?></td>-->
        <td><?php echo $locationContentRow->url ?></td>
        <td><?php echo $locationContentRow->lang ?></td>
        <td><?php echo $locationContentRow->fieldTag ?></td>
        <td><?php echo $locationContentRow->priority ?></td>
        <td><?php echo $this->escape($locationContentRow->content) ?></td>
        <td>
            <?php if ($topEntry) : ?>
            <?php $filename = preg_replace("#/#", ".", $locationContentRow->url) . '.xml'; ?>
            <?php echo $this->prettyDate($locationContentRow->updated, Vfr_View_Helper_PrettyDate::STYLE_DD_MMM_YY_HH_MM) ?><br>            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'xml-parse-location-content', 'action' => 'reload', 'filename' => $filename), null, true) ?>"><button>RELOAD</button></a>
            <button>CHECK</button>
            <button>DELETE</button>
            <?php else : ?>
            &nbsp;
            <?php endif ?>
        </td>
    </tr>
    <?php endforeach ?>
</table>
