<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
</head>
<body>
<div id="doc4">
    <div id="hd"><h1>Villas to rent in Greece, Portugal, Spain, France,<br />Florida and many other holiday destinations<br />around the world including skiing holidays</h1><p><a href="/">Villas to rent</a></p></div>
    <div id="bd">
        <div id="yui-main">
            <div class="yui-b"><?php echo $this->layout()->content ?></div>
        </div>
    </div>

    <div id="ft">
        <span class="left">VillasForRent.NET &copy; 2010</span><span class="right"><a href="#">About</a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;<a href="#">Terms</a
        <p><a href="http://validator.w3.org/check?uri=referer"><img src="http://www.w3.org/Icons/valid-xhtml10-blue" alt="Valid XHTML 1.0 Strict" height="31" width="88" /></a><img alt="All cards accepted" src="/images/cards.gif" /></p>
    </div>
</div>
</body>
</html>
