<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headLink() ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <?php
    //if ($this->jQuery()->isEnabled()) {
        //$this->jQuery()->setLocalPath($this->baseUrl() . 'js/jquery/jquery-1.6.min.js')
          //             ->setUiLocalPath($this->baseUrl() . 'js/jquery-ui-1.8.12/ui/jquery-ui.js')
            //           ->addStylesheet($this->baseUrl() . '/js/jquery-ui-themes-1.8.12/themes/sunny/jquery-ui.css');
      //  echo $this->jQuery();
    //}
    ?>
</head>
<body>
<div id="doc4" class="yui-t2">
    <div id="hd"><h1>Villas to rent in Greece, Portugal, Spain, France,<br />Florida and many other holiday destinations<br />around the world including skiing holidays</h1><p><a href="/">Villas to rent</a></p></div>
    <div id="bd">
        <div id="yui-main">
            <div class="yui-b"><?php echo $this->layout()->content ?></div>
        </div>

        <div class="yui-b">
            <?php //die($this->navigation) ?>
            <h1>New Advertisers</h1>
            <ul>
                <li id="nav-register"><a tabindex="1" accesskey="R" href="/advertiser-registration/register/">register now</a></li>
            </ul>

            <h1>Existing Advertisers</h1>
            <ul>
                <li id="nav-advertiser-login"><a tabindex="3" accesskey="L" href="/advertiser-authentication/login/">login</a></li>
                <li id="nav-advertiser-home"><a tabindex="4" accesskey="H" href="/advertiser-account/home/">account home</a></li>
                <li id="nav-advertiser-logout"><a tabindex="5" accesskey="O" href="/advertiser-authentication/logout/">logout</a></li>
            </ul>
        </div>
    </div>

    <div id="ft">
        <span class="left">VillasForRent.NET &copy; 2010</span><span class="right"><a href="#">About</a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;<a href="#">Terms</a
        <p><a href="http://validator.w3.org/check?uri=referer"><img src="http://www.w3.org/Icons/valid-xhtml10-blue" alt="Valid XHTML 1.0 Strict" height="31" width="88" /></a><img alt="All cards accepted" src="/images/cards.gif" /><a href="http://framework.zend.com/about/casestudies"><img alt="Powered by Zend Framework" src="/images/zend_framework.png" /></a></p>
    </div>
</div>
</body>
</html>
