<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta charset="utf-8">
    <?php
    if (("live" === APPLICATION_ENV) || ("beta" === APPLICATION_ENV)) {
        if ($this->jQuery()->isEnabled()) {
            $this->jQuery()->setCdnSsl(true);
            $this->jQuery()->setVersion('1.7.1');
        }

        if ($this->jQuery()->uiIsEnabled()) {
            $this->jQuery()->setUiVersion('1.8.17');
            $this->jQuery()->addStylesheet('https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/themes/cupertino/jquery-ui.css');
        }

        //$this->headLink()->appendStylesheet('http://yui.yahooapis.com/2.9.0/build/reset-fonts-grids/reset-fonts-grids.css');
        $this->headLink()->appendStylesheet('/js/yui2/reset-fonts-grids/reset-fonts-grids.css');
    } else {
        if ($this->jQuery()->isEnabled()) {
            $this->jQuery()->setLocalPath('/js/jquery/jquery-1.7.1.min.js');
            $this->jQuery()->setUiLocalPath('/js/jquery-ui-1.8.17/js/jquery-ui-1.8.17.custom.min.js');
            $this->jQuery()->addStylesheet('/js/jquery-ui-1.8.17/development-bundle/themes/cupertino/jquery-ui.css');
        }

        $this->headLink()->appendStylesheet('/js/yui2/reset-fonts-grids/reset-fonts-grids.css');
    }
    $this->headLink()->appendStylesheet('/css/villastorent.css');
    $this->headMeta()->appendHttpEquiv('robots', 'ALL');
    ?>
    <?php echo $this->headTitle() . PHP_EOL ?>
    <?php echo $this->headMeta() . PHP_EOL ?>
    <?php echo $this->headLink() . PHP_EOL ?>
    <?php echo $this->jQuery() . PHP_EOL ?>
    <?php echo $this->headScript() . PHP_EOL ?>
    <?php echo $this->headStyle() . PHP_EOL ?>
    <?php if ('live' == APPLICATION_ENV): ?>
        <script>
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-24254189-1']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
        </script>
    <?php endif ?>
</head>
<body>
<div id="doc4">
    <div id="hd">
        <h1>Villas to rent in Greece, Portugal, Spain, France, Florida and many other holiday destinations around the world including skiing holidays</h1>
        <p id="strapline">Dedicated to bringing you the best rental properties from around the world. Book from the owner direct, or advertise YOUR property</p>
        <p id="topnav">
            <a href="/">Home</a>&nbsp;&nbsp;|&nbsp;&nbsp;
            <?php if (!Vfr_Auth_Member::getInstance()->hasIdentity()) : ?>
            <a href="/signup/join">Sign Up</a>&nbsp;&nbsp;|&nbsp;&nbsp;
            <a href="/authentication/login">Login</a>&nbsp;&nbsp;|&nbsp;&nbsp;
            <?php else : ?>
            <a href="/dashboard/home">Hi <?php //echo $this->memberName() ?></a>&nbsp;&nbsp;|&nbsp;&nbsp;
            <?php endif ?>
            <a href="/advertisers/advertise-with-us">Advertise With Us</a>
        </p>
    </div>
    <div id="bd">
        <div id="yui-main">
            <div class="yui-b"><?php echo $this->layout()->content ?></div>
        </div>

        <div class="yui-b">

        </div>
    </div>

    <div id="ft">
        <span class="left">holidaypropertyworldwide.com &copy; 2012</span><span class="right"><a href="#">About</a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;<a href="#">Terms</a
        <p><a href="http://validator.w3.org/check?uri=referer"><img src="/images/other/valid-xhtml10-blue.png" alt="Valid XHTML 1.0 Strict" height="31" width="88" /></a><img alt="All cards accepted" src="/images/cards.gif" /><a href="http://framework.zend.com/about/casestudies"><img alt="Powered by Zend Framework" src="/images/other/zend-framework.png" /></a></p>
    </div>
</div>
</body>
</html>