<h1>Advertiser Password Reminder Sent</h1>
<p>Your password has been emailed to you.</p>

<p>When you receive your password you can <a href="<?php echo $this->url(array('module'     => 'frontend',
                                                                               'controller' => 'advertiser-authentication',
                                                                               'action'     => 'login')) ?>">login to your account</a>


