<?php echo $this->paginationControl($this->featuredPropertiesPaginator, 'Sliding', 'pagination.phtml') ?>

<div style="clear:both" />
<table id="featured-property-list">
    <tr>
        <th>Property ID</th>
        <th>Location</th>
        <th>Featured Box</th>
        <th>Start Date</th>
        <th>Expiry Date</th>
    </tr>
    
    <?php foreach ($this->featuredPropertiesPaginator as $featuredPropertyRow): ?>
    <tr class="<?php echo $this->cycle(array("odd", "even"))->next() ?> <?php echo $this->featuredStatusClass($featuredPropertyRow->startDate, $featuredPropertyRow->expiryDate) ?>">
        <td><?php echo $this->showOnceForGroup($featuredPropertyRow->idProperty) ?></td>
        <td><?php echo $this->escape($featuredPropertyRow->name) ?></td>
        <td><?php echo $this->featuredBoxLabel($featuredPropertyRow->position) ?></td>
        <td><?php echo $this->prettyDate($featuredPropertyRow->startDate, Vfr_View_Helper_PrettyDate::STYLE_DD_MMM_YY) ?></td>
        <td><?php echo $this->prettyDate($featuredPropertyRow->expiryDate, Vfr_View_Helper_PrettyDate::STYLE_DD_MMM_YY) ?></td>
    </tr>
    <?php endforeach ?>
    
</table>