<!--
<table id="property-list">
    <tr>
        <th>idLocation</th>
        <th>lt</th>
        <th>rt</th>
    </tr>
<?php foreach ($this->locationRowset as $locationRow) : ?>
    <tr class="<?php echo $this->cycle(array("odd", "even"))->next() ?>">
        <td><?php echo $locationRow->idLocation ?></td>
        <td><?php echo $locationRow->lt ?></td>
        <td><?php echo $locationRow->rt ?></td>
    </tr>    
<?php endforeach ?>
</table>

-->
