<h1>Welcome to Holiday Property Worldwide, the website dedicated to rental properties from across the world. Book with the owner direct.</h1>

<p><a href="<?php echo $this->url(
				array(
					'module'     => 'frontend',
				    'controller' => 'advertiser-registration',
					'action'	 => 'register'
				)) ?>"><img src="/images/homepage/special_offer.gif" alt="Special Offer - 6 month trial" title="Special Offer - 6 month trial" /></a></p>

<?php if ($this->showFeatured) : ?>
<div class="yui-gb">
    <div class="yui-u first"><?php echo $this->featuredPartials[0] ?></div>
    <div class="yui-u"><?php echo $this->featuredPartials[1] ?></div>
    <div class="yui-u"><?php echo $this->featuredPartials[2] ?></div>
</div>
<?php endif ?>
