<div class="form_advertiser_login">
<h1>Advertiser Forgotten Details</h1>
<p>Use the form below if you have an existing advertiser account with us and have forgotten some or all of your details.</p>

<p>Simply enter your email address or the username (not both) into the appropriate field. Make sure the
email address you provide matches the email address used to setup your account.</p>

<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
<fieldset>
    <dl>
        <dt>
            <label for="emailAddress">Email Account email address:</label>
        </dt>
		<dd>
			<input type="text" name="emailAddress" maxlength="255" value="<?php echo $this->escape($this->form->getValue('emailAddress')) ?>" />
			<?php echo $this->displayErrors($this->form->getMessages('emailAddress')) ?>
		</dd>
		
		<input type="submit" name="submit" value="Login" />
</fieldset>
</form>
</div>
