<h1>Account Email Confirmation Failed</h1>
<p>You have attempted to change your account email to an email address that is associated to another active account.</p>

<p>If you are trying to merge properties between accounts, please contact support directly.</p>

<p>Return to <a href="<?php echo $this->url(array('module' => 'controlpanel', 'controller' => 'account-settings', 'action' => 'list')) ?>">account settings</a> if you still wish to change the account email.</p>
